/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdvanceRepoWatermarkBody {
    'repository'?: string;
    /**
     * Full git commit sha to advance to.
     */
    'sha'?: string;
    /**
     * baseline (insert-only, first contact), empty_sync (CAS on expected_current_sha), or bootstrap (unconditional — explicit full re-generation). sync_merge and ingest are internal writers (the branch merge hook and the codebase agent) and are rejected here.
     */
    'reason'?: string;
    /**
     * Required for empty_sync: the watermark value the caller\'s detection saw. The advance is a compare-and-set on it — a lost ordering race returns advanced=false instead of overwriting.
     */
    'expectedCurrentSha'?: string;
}

