/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * AgentRunEvent is one timestamped log entry of an agent run: level + kind + human-readable message, with optional structured data_json.
 */
export interface AgentRunEvent {
    'id'?: string;
    'runId'?: string;
    'ts'?: string;
    'level'?: string;
    'kind'?: string;
    'message'?: string;
    'dataJson'?: string;
}

