/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AttributedRequirementComponent } from './attributed-requirement-component';

export interface AttributeRequirementComponentsResponse {
    /**
     * Requirements newly attributed this run. Bounded (see maxReturnedAttributedRequirements in the service implementation) so a large product\'s backfill can\'t exceed the gRPC max message size; the DB write itself is unbounded — attributed_count is the true total.
     */
    'attributed'?: Array<AttributedRequirementComponent>;
    'attributedCount'?: number;
    /**
     * Requirements whose repo_file anchors resolved to more than one distinct component — left untouched.
     */
    'skippedMultiComponentCount'?: number;
    /**
     * Requirements whose repo_file anchors resolved to no component at all (including a repository-ambiguous anchor path) — left untouched.
     */
    'skippedUnownedCount'?: number;
    /**
     * Requirements evaluated: main-branch, non-deleted, component_id NULL, with at least one repo_file anchor.
     */
    'consideredCount'?: number;
}

