/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AttributedChangedFile } from './attributed-changed-file';
// May contain unused imports in some cases
// @ts-ignore
import type { ChangedFile } from './changed-file';

export interface AttributeChangedFilesResponse {
    'attributed'?: Array<AttributedChangedFile>;
    'unmatched'?: Array<ChangedFile>;
    /**
     * component_id is set when the files resolve to exactly ONE component (requirement.component_id was set to it); empty when they span multiple components (cleared) or none.
     */
    'componentId'?: string;
}

