/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * AttributedRequirementComponent is one requirement newly attributed to a component from its own repo_file anchors this run.
 */
export interface AttributedRequirementComponent {
    'requirementId'?: string;
    'requirementSeq'?: number;
    'requirementTitle'?: string;
    'componentId'?: string;
    'componentName'?: string;
}

