/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * BranchLatestRun is the most recent test_runs row attributed to a branch (by branch_id, or by intent_branch/branch_name when live-doc sync never resolved branch_id — see BranchLoopStats\' sibling doc on TestRunRepository.LatestAndCountByBranchForProduct), plus how many runs in total are attributed to it. Populated only by ListBranches with include_status=true.
 */
export interface BranchLatestRun {
    'seqNum'?: number;
    'status'?: string;
    'startedAt'?: string;
    'completedAt'?: string;
    'total'?: number;
    'passed'?: number;
    'failed'?: number;
}

