/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ChangedFile is one repo-qualified changed path.
 */
export interface ChangedFile {
    /**
     * repository is the canonical repo id OR a local checkout alias (resolved via component repository_aliases).
     */
    'repository'?: string;
    /**
     * path is repo-relative.
     */
    'path'?: string;
    /**
     * status is \"modified\"|\"added\"|\"deleted\" (informational — deleted files are still attributed to their component; the caller decides not to anchor them).
     */
    'status'?: string;
}

