/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DeclareRequirementEdgeIntent records a deferred semantic edge for a brand-new feature whose endpoint(s) are not yet on main. The intent is stored on the branch and materialized into a real edge when the branch merges to main.
 */
export interface DeclareRequirementEdgeIntentBody {
    /**
     * branch is the branch the intent is declared on (empty = main).
     */
    'branch'?: string;
    'srcRequirementId'?: string;
    /**
     * Exactly one dst endpoint (see WriteRequirementEdgeRequest). dst_requirement_id may be empty when dst_component_id is set.
     */
    'dstRequirementId'?: string;
    /**
     * edge_type must be \"depends_on\"/\"traces_to\" (req→req) or \"impacts_component\" (req→component).
     */
    'edgeType'?: string;
    /**
     * confidence must be provided; explicit 0.0 is valid, omitted is not.
     */
    'confidence'?: number;
    'rationale'?: string;
    /**
     * dst_component_id sets a req→component endpoint. Mutually exclusive with dst_requirement_id.
     */
    'dstComponentId'?: string;
}

