/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeleteRequirementResponse {
    /**
     * Id of the recorded deletion history event. Pass it to RestoreRequirement to undo the delete. Empty for deletes that record no undoable event.
     */
    'historyId'?: string;
}

