/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DistillIntentRequest carries one coding session — the rendered transcript plus session metadata — to reconcile into the product\'s requirement tree.
 */
export interface DistillIntentBody {
    /**
     * Rendered conversation (normalized, slim — user/assistant text only). The backend never sees an agent-specific transcript format.
     */
    'transcript'?: string;
    /**
     * Optional LLM credential to use. When empty, the backend picks the first usable llm.* credential in the product\'s workspace.
     */
    'credentialId'?: string;
    /**
     * Optional model override; when empty, falls back to the credential\'s metadata \"model\" field.
     */
    'model'?: string;
    /**
     * Optional branch slug override; when empty, defaults to \"session\".
     */
    'slug'?: string;
    /**
     * Repo-relative paths of files changed in the coding session (from git post-commit hook). The backend validates LLM-emitted repo_file anchors against this allowlist, dropping any path not in the set. Empty = no anchors written (backward-compatible: older CLI sends nothing).
     */
    'changedFiles'?: Array<string>;
    /**
     * Coding-session identity. When either is set, every created/updated requirement gets a manual_input \"Intent capture\" provenance source carrying {sessionId, agent}, so a reviewer can trace it back to the session that produced it. Both empty (older CLI) writes no provenance source.
     */
    'sessionId'?: string;
    'agent'?: string;
}

