/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Environment labels where test runs and releases happen (e.g. production, staging). slug is the stable identifier reporters and CI reference; origin is \"manual\" (created explicitly) or \"auto\" (auto-created by an ingest endpoint from an unknown slug).
 */
export interface Environment {
    'id'?: string;
    'productId'?: string;
    'name'?: string;
    'slug'?: string;
    'description'?: string;
    'host'?: string;
    'type'?: string;
    'origin'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}

