/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Frame is one server-resolved stacktrace frame. state drives the UI treatment (resolved=quiet, map_missing/map_mismatch=amber badge, degraded=banner).
 */
export interface Frame {
    'function'?: string;
    'absPath'?: string;
    'filename'?: string;
    'lineno'?: number;
    'colno'?: number;
    'inApp'?: boolean;
    'state'?: string;
    'contextLine'?: string;
    'preContext'?: Array<string>;
    'postContext'?: Array<string>;
}

