/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Component } from './component';
// May contain unused imports in some cases
// @ts-ignore
import type { ComponentMergeModification } from './component-merge-modification';
// May contain unused imports in some cases
// @ts-ignore
import type { MergeModification } from './merge-modification';
// May contain unused imports in some cases
// @ts-ignore
import type { MergeStats } from './merge-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { Requirement } from './requirement';
// May contain unused imports in some cases
// @ts-ignore
import type { Test } from './test';
// May contain unused imports in some cases
// @ts-ignore
import type { TestMergeModification } from './test-merge-modification';

export interface GetMergePreviewResponse {
    'additions'?: Array<Requirement>;
    'modifications'?: Array<MergeModification>;
    'deletions'?: Array<Requirement>;
    'stats'?: MergeStats;
    /**
     * Test-side merge effects (Phase 4 extension). Empty when the branch holds no test changes.
     */
    'testAdditions'?: Array<Test>;
    'testModifications'?: Array<TestMergeModification>;
    'testDeletions'?: Array<Test>;
    /**
     * Component-side merge effects. Empty when the branch holds no component changes.
     */
    'componentAdditions'?: Array<Component>;
    'componentModifications'?: Array<ComponentMergeModification>;
    'componentDeletions'?: Array<Component>;
}

