/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionProgressRequirement } from './session-progress-requirement';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionProgressSummary } from './session-progress-summary';

export interface GetSessionProgressResponse {
    'requirements'?: Array<SessionProgressRequirement>;
    'summary'?: SessionProgressSummary;
    'ready'?: boolean;
    'nextActions'?: Array<string>;
    'intentBranchStatus'?: string;
}

