/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ImpactCoverage distinguishes the three ways an impact answer can be empty or partial. Before this existed all three returned an identical empty response.
 */
export interface ImpactCoverage {
    /**
     * requested_paths is how many repo paths the caller sent.
     */
    'requestedPaths'?: number;
    /**
     * matched_paths is how many of them are anchored to at least one requirement. 0 with product_has_anchors = true means \"we cannot tell\", not \"nothing\".
     */
    'matchedPaths'?: number;
    /**
     * product_has_anchors is false when the product has no repo_file anchors at all — an empty answer then says nothing about the change.
     */
    'productHasAnchors'?: boolean;
    /**
     * unmatched_paths is the requested paths that matched no anchor (capped).
     */
    'unmatchedPaths'?: Array<string>;
    /**
     * blind_directories is the directories among unmatched_paths under which the product has no anchor at all — i.e. tiers we are structurally blind to.
     */
    'blindDirectories'?: Array<string>;
    /**
     * unverified_repository_seeds counts seeds kept without a repository check because their requirement has no component. Only set when request.repository is non-empty; it should fall to 0 as components get assigned.
     */
    'unverifiedRepositorySeeds'?: number;
}

