/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IngestTest } from './ingest-test';

/**
 * IngestTestsRequest is one reporter batch: 1..1000 tests upserted into (product, branch) with a shared framework label.
 */
export interface IngestTestsBody {
    'branch'?: string;
    /**
     * pytest | jest | junit | ...
     */
    'framework'?: string;
    'tests'?: Array<IngestTest>;
}

