/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Component } from './component';
// May contain unused imports in some cases
// @ts-ignore
import type { Issue } from './issue';
// May contain unused imports in some cases
// @ts-ignore
import type { IssueEnvironmentCount } from './issue-environment-count';
// May contain unused imports in some cases
// @ts-ignore
import type { IssueEvent } from './issue-event';
// May contain unused imports in some cases
// @ts-ignore
import type { SuspectRequirement } from './suspect-requirement';

/**
 * IssueFixContext is everything needed to fix one error, in one response: what broke, where it is happening, which files the stack trace implicates, which requirements those files implement, and whether any test covers them.
 */
export interface IssueFixContext {
    'issue'?: Issue;
    'latestEvent'?: IssueEvent;
    /**
     * suspect_paths are the file paths of the in-app stack frames, in stack order and deduplicated. These are the files to open.
     */
    'suspectPaths'?: Array<string>;
    /**
     * environments is the per-environment occurrence split — how you tell a production outage from dev noise.
     */
    'environments'?: Array<IssueEnvironmentCount>;
    'firstReleaseName'?: string;
    'lastReleaseName'?: string;
    /**
     * regressed is true when this issue was resolved and came back, reopening automatically. Treat these as highest priority.
     */
    'regressed'?: boolean;
    'component'?: Component;
    'suspectRequirements'?: Array<SuspectRequirement>;
    /**
     * truncation_signals names anything omitted to keep the response bounded.
     */
    'truncationSignals'?: Array<string>;
}

