/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Issue } from './issue';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationResponse } from './pagination-response';

export interface ListIssuesResponse {
    'issues'?: Array<Issue>;
    'pagination'?: PaginationResponse;
    /**
     * true when ungrouped events exist for this product (worker hasn\'t caught up); drives the \"Receiving events, grouping…\" banner.
     */
    'processing'?: boolean;
}

