/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MergeBranchBody {
    /**
     * Resolution map keys are prefixed: \"req:<uuid>\", \"test:<uuid>\", or \"comp:<uuid>\". Server accepts un-prefixed keys as `req:` for v1 backwards compat (deprecated; logged with warning, removal scheduled for v2).
     */
    'resolutions'?: { [key: string]: string; };
}

