/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PaginationRequest is the shared cursor-pagination input: page_size caps the page (server default and maximum apply when 0 or out of range) and page_token continues from a previous response\'s next_page_token.
 */
export interface PaginationRequest {
    'pageSize'?: number;
    'pageToken'?: string;
}

