/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Product is the top-level container for requirements, tests, runs, and releases. code is the reference prefix for entity sequence numbers ({CODE}-{seq}).
 */
export interface Product {
    'id'?: string;
    'workspaceId'?: string;
    'name'?: string;
    'description'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'code'?: string;
    /**
     * Gates live-documentation mode: on test-run completion the test repository is reconciled from the run\'s results. Default on.
     */
    'liveDocEnabled'?: boolean;
    /**
     * Team owner. Empty = workspace-owned (visible to all workspace members); set = team-owned (visible to that team\'s members + workspace owners/admins).
     */
    'teamId'?: string;
}

