/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RadiusDrop is one requirement a session judged out of the diff\'s radius. Recorded as a radius_drop judgement under its supersede key. seq is an optional display hint (e.g. the requirement\'s product seq_num) for the caller\'s own logging — not persisted server-side.
 */
export interface RadiusDrop {
    'requirementId'?: string;
    'reason'?: string;
    'seq'?: number;
}

