/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntentSessionNothingToDistill } from './intent-session-nothing-to-distill';
// May contain unused imports in some cases
// @ts-ignore
import type { IntentSessionSettlementItem } from './intent-session-settlement-item';

export interface RecordSessionSettlementBody {
    /**
     * items and nothing_to_distill are mutually exclusive; items are merged by item_id onto the stored settlement, nothing_to_distill replaces it wholesale. See IntentSessionService.RecordSessionSettlement for the full semantics.
     */
    'items'?: Array<IntentSessionSettlementItem>;
    'nothingToDistill'?: IntentSessionNothingToDistill;
}

