/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentMemoryContext } from './agent-memory-context';
// May contain unused imports in some cases
// @ts-ignore
import type { Component } from './component';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextCitation } from './context-citation';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextTest } from './context-test';
// May contain unused imports in some cases
// @ts-ignore
import type { Requirement } from './requirement';
// May contain unused imports in some cases
// @ts-ignore
import type { RequirementSource } from './requirement-source';
// May contain unused imports in some cases
// @ts-ignore
import type { RequirementTestFields } from './requirement-test-fields';
// May contain unused imports in some cases
// @ts-ignore
import type { StaleCoverageSignal } from './stale-coverage-signal';

/**
 * RequirementTestContext is the full test-authoring context pack for one requirement: its tree family, component, related tests by link kind, staleness signals, extracted test-oriented fields, agent memory, and the citations resolving every citation_id used in the pack.
 */
export interface RequirementTestContext {
    'requirement'?: Requirement;
    'parent'?: Requirement;
    'children'?: Array<Requirement>;
    'siblings'?: Array<Requirement>;
    'component'?: Component;
    'linkedTests'?: Array<ContextTest>;
    'proposedTests'?: Array<ContextTest>;
    'relevantTests'?: Array<ContextTest>;
    'staleSignals'?: Array<StaleCoverageSignal>;
    'extractedFields'?: RequirementTestFields;
    'memoryEntries'?: Array<AgentMemoryContext>;
    'citations'?: Array<ContextCitation>;
    'sources'?: Array<RequirementSource>;
    'truncationSignals'?: Array<string>;
}

