/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RequirementImpactResponse {
    /**
     * affected is the full set of requirement IDs reachable from the file seeds.
     */
    'affectedRequirementIds'?: Array<string>;
    /**
     * covering_test_ids is the set of test IDs covering at least one affected requirement.
     */
    'coveringTestIds'?: Array<string>;
    /**
     * uncovered_requirement_ids is the subset of affected that have zero live test links.
     */
    'uncoveredRequirementIds'?: Array<string>;
}

