/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionProgressTest } from './session-progress-test';

/**
 * SessionProgressRequirement is one requirement\'s coverage ladder step.
 */
export interface SessionProgressRequirement {
    'requirementId'?: string;
    'display'?: string;
    'title'?: string;
    'coverage'?: string;
    'proposedOnly'?: boolean;
    'movedThisSession'?: boolean;
    'tests'?: Array<SessionProgressTest>;
    /**
     * Not in the caller\'s requested slice — added because a test this session executed links to it. Informational: adopted rows are excluded from summary/ready/next_actions (a broad validation run must not hold the session\'s readiness hostage to requirements it never touched).
     */
    'adopted'?: boolean;
}

