/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SourceMap is the metadata of one uploaded source map, keyed by debug_id for matching against incoming error events.
 */
export interface SourceMap {
    'id'?: string;
    'productId'?: string;
    'debugId'?: string;
    'fileName'?: string;
    'releaseName'?: string;
    'byteSize'?: string;
    /**
     * NOTE: metadata only — never an S3 download URL (maps are private source).
     */
    'createdAt'?: string;
}

