/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StartAgentRunBody {
    /**
     * inputs_override may override inputs_json on the config for this run only. Useful for \"Run with these URLs\" without persisting them on the config.
     */
    'inputsOverrideJson'?: string;
}

