/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LiveDocStats } from './live-doc-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStats } from './run-stats';

/**
 * TestRun is the API projection of one CI execution container.
 */
export interface TestRun {
    'id'?: string;
    'productId'?: string;
    'seqNum'?: number;
    'title'?: string;
    'description'?: string;
    'status'?: string;
    'environmentId'?: string;
    'environmentSlug'?: string;
    'environmentName'?: string;
    'branchName'?: string;
    'branchId'?: string;
    'configurations'?: { [key: string]: string; };
    'buildSha'?: string;
    'clientMeta'?: { [key: string]: string; };
    'stats'?: RunStats;
    'startedAt'?: string;
    'completedAt'?: string;
    'liveDocStatus'?: string;
    'liveDocOperationId'?: string;
    'liveDocStats'?: LiveDocStats;
    'liveDocError'?: string;
    'createdBy'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'intentSessionId'?: string;
    'intentBranch'?: string;
}

