/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TestRequirementLink is one durable test-case-to-requirement coverage link on main; linked cases\' executions count toward the requirement\'s coverage.
 */
export interface TestRequirementLink {
    'id'?: string;
    'testId'?: string;
    'requirementId'?: string;
    'createdAt'?: string;
}

