/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TestExecution } from './test-execution';
// May contain unused imports in some cases
// @ts-ignore
import type { TestParameterGroup } from './test-parameter-group';
// May contain unused imports in some cases
// @ts-ignore
import type { TestRelation } from './test-relation';
// May contain unused imports in some cases
// @ts-ignore
import type { TestStep } from './test-step';

export interface UpdateTestBody {
    'branch'?: string;
    'title'?: string;
    'description'?: string;
    'parentId'?: string;
    'position'?: number;
    'status'?: string;
    'priority'?: string;
    'type'?: string;
    'layer'?: string;
    'muted'?: boolean;
    'componentId'?: string;
    'assigneeId'?: string;
    /**
     * Replacement semantics: if a field is set on the request, it replaces the entire stored value. Use empty list/struct to clear.
     */
    'setTags'?: boolean;
    'tags'?: Array<string>;
    'setCustomFields'?: boolean;
    'customFields'?: object;
    'setSteps'?: boolean;
    'steps'?: Array<TestStep>;
    'isAutomated'?: boolean;
    'signature'?: string;
    'testopsId'?: number;
    'clearTestopsId'?: boolean;
    'authorType'?: string;
    'authorId'?: string;
    'authorName'?: string;
    'setParameterGroups'?: boolean;
    'parameterGroups'?: Array<TestParameterGroup>;
    'setLatestExecution'?: boolean;
    'latestExecution'?: TestExecution;
    'setAttachments'?: boolean;
    'attachments'?: Array<string>;
    'setRelations'?: boolean;
    'relations'?: Array<TestRelation>;
}

