/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateComponentBody {
    /**
     * name/description use proto3 presence: an OMITTED field is left unchanged; a present field (even empty) is applied. Prevents a partial update that only sets repository scope from clobbering name/description to \"\".
     */
    'name'?: string;
    'description'?: string;
    'branch'?: string;
    'repository'?: string;
    'setRepository'?: boolean;
    'componentPaths'?: Array<string>;
    'setComponentPaths'?: boolean;
    'repositoryAliases'?: Array<string>;
    'setRepositoryAliases'?: boolean;
}

