/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AttributeChangedFilesBody } from '../model';
// @ts-ignore
import type { AttributeChangedFilesResponse } from '../model';
// @ts-ignore
import type { DeclareRequirementEdgeIntentBody } from '../model';
// @ts-ignore
import type { DeclareRequirementEdgeIntentResponse } from '../model';
// @ts-ignore
import type { GetRequirementGraphResponse } from '../model';
// @ts-ignore
import type { GetRequirementTestContextResponse } from '../model';
// @ts-ignore
import type { GraphCoverageGapsResponse } from '../model';
// @ts-ignore
import type { ListCoverageGapsResponse } from '../model';
// @ts-ignore
import type { ListRequirementAnchorsResponse } from '../model';
// @ts-ignore
import type { PrepareTestGenerationContextBody } from '../model';
// @ts-ignore
import type { PrepareTestGenerationContextResponse } from '../model';
// @ts-ignore
import type { RequirementImpactResponse } from '../model';
// @ts-ignore
import type { RequirementNeighborsResponse } from '../model';
// @ts-ignore
import type { ResolveFeatureContextResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { WriteRequirementEdgeBody } from '../model';
// @ts-ignore
import type { WriteRequirementEdgeResponse } from '../model';
/**
 * AgentRetrievalServiceApi - axios parameter creator
 */
export const AgentRetrievalServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {AttributeChangedFilesBody} attributeChangedFilesBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceAttributeChangedFiles: async (productId: string, requirementId: string, attributeChangedFilesBody: AttributeChangedFilesBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceAttributeChangedFiles', 'productId', productId)
            // verify required parameter 'requirementId' is not null or undefined
            assertParamExists('agentRetrievalServiceAttributeChangedFiles', 'requirementId', requirementId)
            // verify required parameter 'attributeChangedFilesBody' is not null or undefined
            assertParamExists('agentRetrievalServiceAttributeChangedFiles', 'attributeChangedFilesBody', attributeChangedFilesBody)
            const localVarPath = `/v1/products/{productId}/requirements/{requirementId}:attribute-changed-files`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"requirementId"}}`, encodeURIComponent(String(requirementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(attributeChangedFilesBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {DeclareRequirementEdgeIntentBody} declareRequirementEdgeIntentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceDeclareRequirementEdgeIntent: async (productId: string, declareRequirementEdgeIntentBody: DeclareRequirementEdgeIntentBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceDeclareRequirementEdgeIntent', 'productId', productId)
            // verify required parameter 'declareRequirementEdgeIntentBody' is not null or undefined
            assertParamExists('agentRetrievalServiceDeclareRequirementEdgeIntent', 'declareRequirementEdgeIntentBody', declareRequirementEdgeIntentBody)
            const localVarPath = `/v1/products/{productId}/requirement-edge-intents`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(declareRequirementEdgeIntentBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGetRequirementGraph: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceGetRequirementGraph', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/requirement-graph`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {string} [branch] 
         * @param {number} [budget] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGetRequirementTestContext: async (productId: string, requirementId: string, branch?: string, budget?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceGetRequirementTestContext', 'productId', productId)
            // verify required parameter 'requirementId' is not null or undefined
            assertParamExists('agentRetrievalServiceGetRequirementTestContext', 'requirementId', requirementId)
            const localVarPath = `/v1/products/{productId}/requirements/{requirementId}/test-context`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"requirementId"}}`, encodeURIComponent(String(requirementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            if (budget !== undefined) {
                localVarQueryParameter['budget'] = budget;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {Array<string>} [requirementIds] requirement_ids is the set to check for coverage. Typically the result of RequirementImpact or RequirementNeighbors.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGraphCoverageGaps: async (productId: string, requirementIds?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceGraphCoverageGaps', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/requirements/graph-coverage-gaps`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (requirementIds) {
                localVarQueryParameter['requirementIds'] = requirementIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] 
         * @param {Array<string>} [coverageStatuses] 
         * @param {string} [componentId] 
         * @param {string} [query] 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [rootRequirementId] scope gaps to a feature subtree (root + descendants)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceListCoverageGaps: async (productId: string, branch?: string, coverageStatuses?: Array<string>, componentId?: string, query?: string, paginationPageSize?: number, paginationPageToken?: string, rootRequirementId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceListCoverageGaps', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/coverage-gaps`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            if (coverageStatuses) {
                localVarQueryParameter['coverageStatuses'] = coverageStatuses;
            }

            if (componentId !== undefined) {
                localVarQueryParameter['componentId'] = componentId;
            }

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            if (rootRequirementId !== undefined) {
                localVarQueryParameter['rootRequirementId'] = rootRequirementId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] empty &#x3D; main
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceListRequirementAnchors: async (productId: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceListRequirementAnchors', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/requirement-anchors`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {PrepareTestGenerationContextBody} prepareTestGenerationContextBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServicePrepareTestGenerationContext: async (productId: string, prepareTestGenerationContextBody: PrepareTestGenerationContextBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServicePrepareTestGenerationContext', 'productId', productId)
            // verify required parameter 'prepareTestGenerationContextBody' is not null or undefined
            assertParamExists('agentRetrievalServicePrepareTestGenerationContext', 'prepareTestGenerationContextBody', prepareTestGenerationContextBody)
            const localVarPath = `/v1/products/{productId}/test-generation-context:prepare`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(prepareTestGenerationContextBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {Array<string>} [repoPaths] repo_paths is the set of changed file paths (e.g. from a merged PR). The backend resolves these to seeded requirement IDs via requirement_sources.
         * @param {number} [depth] depth controls how many hops the graph traversal expands beyond the seeds. Defaults to 3 on the server if &lt;&#x3D; 0.
         * @param {Array<string>} [edgeTypes] edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceRequirementImpact: async (productId: string, repoPaths?: Array<string>, depth?: number, edgeTypes?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceRequirementImpact', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/requirements/impact`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (repoPaths) {
                localVarQueryParameter['repoPaths'] = repoPaths;
            }

            if (depth !== undefined) {
                localVarQueryParameter['depth'] = depth;
            }

            if (edgeTypes) {
                localVarQueryParameter['edgeTypes'] = edgeTypes;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {number} [depth] depth controls how many hops to traverse (default 1 if &lt;&#x3D; 0).
         * @param {Array<string>} [edgeTypes] edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceRequirementNeighbors: async (productId: string, requirementId: string, depth?: number, edgeTypes?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceRequirementNeighbors', 'productId', productId)
            // verify required parameter 'requirementId' is not null or undefined
            assertParamExists('agentRetrievalServiceRequirementNeighbors', 'requirementId', requirementId)
            const localVarPath = `/v1/products/{productId}/requirements/{requirementId}/neighbors`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"requirementId"}}`, encodeURIComponent(String(requirementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (depth !== undefined) {
                localVarQueryParameter['depth'] = depth;
            }

            if (edgeTypes) {
                localVarQueryParameter['edgeTypes'] = edgeTypes;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] empty &#x3D; main
         * @param {string} [text] text is the free-text coding objective to resolve into feature context.
         * @param {Array<string>} [repoPaths] repo_paths are optional changed file paths that seed anchor retrieval.
         * @param {number} [k] k bounds each retrieval signal\&#39;s breadth (server default when &lt;&#x3D; 0).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceResolveFeatureContext: async (productId: string, branch?: string, text?: string, repoPaths?: Array<string>, k?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceResolveFeatureContext', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/feature-context`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }

            if (repoPaths) {
                localVarQueryParameter['repoPaths'] = repoPaths;
            }

            if (k !== undefined) {
                localVarQueryParameter['k'] = k;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {WriteRequirementEdgeBody} writeRequirementEdgeBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceWriteRequirementEdge: async (productId: string, writeRequirementEdgeBody: WriteRequirementEdgeBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('agentRetrievalServiceWriteRequirementEdge', 'productId', productId)
            // verify required parameter 'writeRequirementEdgeBody' is not null or undefined
            assertParamExists('agentRetrievalServiceWriteRequirementEdge', 'writeRequirementEdgeBody', writeRequirementEdgeBody)
            const localVarPath = `/v1/products/{productId}/requirement-edges`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(writeRequirementEdgeBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgentRetrievalServiceApi - functional programming interface
 */
export const AgentRetrievalServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AgentRetrievalServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {AttributeChangedFilesBody} attributeChangedFilesBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceAttributeChangedFiles(productId: string, requirementId: string, attributeChangedFilesBody: AttributeChangedFilesBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttributeChangedFilesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceAttributeChangedFiles(productId, requirementId, attributeChangedFilesBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceAttributeChangedFiles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {DeclareRequirementEdgeIntentBody} declareRequirementEdgeIntentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceDeclareRequirementEdgeIntent(productId: string, declareRequirementEdgeIntentBody: DeclareRequirementEdgeIntentBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeclareRequirementEdgeIntentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceDeclareRequirementEdgeIntent(productId, declareRequirementEdgeIntentBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceDeclareRequirementEdgeIntent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceGetRequirementGraph(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRequirementGraphResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceGetRequirementGraph(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceGetRequirementGraph']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {string} [branch] 
         * @param {number} [budget] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceGetRequirementTestContext(productId: string, requirementId: string, branch?: string, budget?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRequirementTestContextResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceGetRequirementTestContext(productId, requirementId, branch, budget, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceGetRequirementTestContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {Array<string>} [requirementIds] requirement_ids is the set to check for coverage. Typically the result of RequirementImpact or RequirementNeighbors.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceGraphCoverageGaps(productId: string, requirementIds?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GraphCoverageGapsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceGraphCoverageGaps(productId, requirementIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceGraphCoverageGaps']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] 
         * @param {Array<string>} [coverageStatuses] 
         * @param {string} [componentId] 
         * @param {string} [query] 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [rootRequirementId] scope gaps to a feature subtree (root + descendants)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceListCoverageGaps(productId: string, branch?: string, coverageStatuses?: Array<string>, componentId?: string, query?: string, paginationPageSize?: number, paginationPageToken?: string, rootRequirementId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListCoverageGapsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceListCoverageGaps(productId, branch, coverageStatuses, componentId, query, paginationPageSize, paginationPageToken, rootRequirementId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceListCoverageGaps']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] empty &#x3D; main
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceListRequirementAnchors(productId: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListRequirementAnchorsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceListRequirementAnchors(productId, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceListRequirementAnchors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {PrepareTestGenerationContextBody} prepareTestGenerationContextBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServicePrepareTestGenerationContext(productId: string, prepareTestGenerationContextBody: PrepareTestGenerationContextBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PrepareTestGenerationContextResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServicePrepareTestGenerationContext(productId, prepareTestGenerationContextBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServicePrepareTestGenerationContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {Array<string>} [repoPaths] repo_paths is the set of changed file paths (e.g. from a merged PR). The backend resolves these to seeded requirement IDs via requirement_sources.
         * @param {number} [depth] depth controls how many hops the graph traversal expands beyond the seeds. Defaults to 3 on the server if &lt;&#x3D; 0.
         * @param {Array<string>} [edgeTypes] edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceRequirementImpact(productId: string, repoPaths?: Array<string>, depth?: number, edgeTypes?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequirementImpactResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceRequirementImpact(productId, repoPaths, depth, edgeTypes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceRequirementImpact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} requirementId 
         * @param {number} [depth] depth controls how many hops to traverse (default 1 if &lt;&#x3D; 0).
         * @param {Array<string>} [edgeTypes] edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceRequirementNeighbors(productId: string, requirementId: string, depth?: number, edgeTypes?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequirementNeighborsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceRequirementNeighbors(productId, requirementId, depth, edgeTypes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceRequirementNeighbors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [branch] empty &#x3D; main
         * @param {string} [text] text is the free-text coding objective to resolve into feature context.
         * @param {Array<string>} [repoPaths] repo_paths are optional changed file paths that seed anchor retrieval.
         * @param {number} [k] k bounds each retrieval signal\&#39;s breadth (server default when &lt;&#x3D; 0).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceResolveFeatureContext(productId: string, branch?: string, text?: string, repoPaths?: Array<string>, k?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResolveFeatureContextResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceResolveFeatureContext(productId, branch, text, repoPaths, k, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceResolveFeatureContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {WriteRequirementEdgeBody} writeRequirementEdgeBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRetrievalServiceWriteRequirementEdge(productId: string, writeRequirementEdgeBody: WriteRequirementEdgeBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WriteRequirementEdgeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRetrievalServiceWriteRequirementEdge(productId, writeRequirementEdgeBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRetrievalServiceApi.agentRetrievalServiceWriteRequirementEdge']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AgentRetrievalServiceApi - factory interface
 */
export const AgentRetrievalServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AgentRetrievalServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceAttributeChangedFilesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceAttributeChangedFiles(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceAttributeChangedFilesRequest, options?: RawAxiosRequestConfig): AxiosPromise<AttributeChangedFilesResponse> {
            return localVarFp.agentRetrievalServiceAttributeChangedFiles(requestParameters.productId, requestParameters.requirementId, requestParameters.attributeChangedFilesBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceDeclareRequirementEdgeIntent(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeclareRequirementEdgeIntentResponse> {
            return localVarFp.agentRetrievalServiceDeclareRequirementEdgeIntent(requestParameters.productId, requestParameters.declareRequirementEdgeIntentBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementGraphRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGetRequirementGraph(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementGraphRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetRequirementGraphResponse> {
            return localVarFp.agentRetrievalServiceGetRequirementGraph(requestParameters.productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementTestContextRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGetRequirementTestContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementTestContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetRequirementTestContextResponse> {
            return localVarFp.agentRetrievalServiceGetRequirementTestContext(requestParameters.productId, requestParameters.requirementId, requestParameters.branch, requestParameters.budget, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceGraphCoverageGapsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceGraphCoverageGaps(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGraphCoverageGapsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GraphCoverageGapsResponse> {
            return localVarFp.agentRetrievalServiceGraphCoverageGaps(requestParameters.productId, requestParameters.requirementIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceListCoverageGapsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceListCoverageGaps(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceListCoverageGapsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListCoverageGapsResponse> {
            return localVarFp.agentRetrievalServiceListCoverageGaps(requestParameters.productId, requestParameters.branch, requestParameters.coverageStatuses, requestParameters.componentId, requestParameters.query, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.rootRequirementId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceListRequirementAnchorsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceListRequirementAnchors(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceListRequirementAnchorsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListRequirementAnchorsResponse> {
            return localVarFp.agentRetrievalServiceListRequirementAnchors(requestParameters.productId, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServicePrepareTestGenerationContextRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServicePrepareTestGenerationContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServicePrepareTestGenerationContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PrepareTestGenerationContextResponse> {
            return localVarFp.agentRetrievalServicePrepareTestGenerationContext(requestParameters.productId, requestParameters.prepareTestGenerationContextBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceRequirementImpactRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceRequirementImpact(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceRequirementImpactRequest, options?: RawAxiosRequestConfig): AxiosPromise<RequirementImpactResponse> {
            return localVarFp.agentRetrievalServiceRequirementImpact(requestParameters.productId, requestParameters.repoPaths, requestParameters.depth, requestParameters.edgeTypes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceRequirementNeighborsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceRequirementNeighbors(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceRequirementNeighborsRequest, options?: RawAxiosRequestConfig): AxiosPromise<RequirementNeighborsResponse> {
            return localVarFp.agentRetrievalServiceRequirementNeighbors(requestParameters.productId, requestParameters.requirementId, requestParameters.depth, requestParameters.edgeTypes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceResolveFeatureContextRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceResolveFeatureContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceResolveFeatureContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResolveFeatureContextResponse> {
            return localVarFp.agentRetrievalServiceResolveFeatureContext(requestParameters.productId, requestParameters.branch, requestParameters.text, requestParameters.repoPaths, requestParameters.k, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRetrievalServiceApiAgentRetrievalServiceWriteRequirementEdgeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRetrievalServiceWriteRequirementEdge(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceWriteRequirementEdgeRequest, options?: RawAxiosRequestConfig): AxiosPromise<WriteRequirementEdgeResponse> {
            return localVarFp.agentRetrievalServiceWriteRequirementEdge(requestParameters.productId, requestParameters.writeRequirementEdgeBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for agentRetrievalServiceAttributeChangedFiles operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceAttributeChangedFilesRequest {
    readonly productId: string

    readonly requirementId: string

    readonly attributeChangedFilesBody: AttributeChangedFilesBody
}

/**
 * Request parameters for agentRetrievalServiceDeclareRequirementEdgeIntent operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest {
    readonly productId: string

    readonly declareRequirementEdgeIntentBody: DeclareRequirementEdgeIntentBody
}

/**
 * Request parameters for agentRetrievalServiceGetRequirementGraph operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementGraphRequest {
    readonly productId: string
}

/**
 * Request parameters for agentRetrievalServiceGetRequirementTestContext operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementTestContextRequest {
    readonly productId: string

    readonly requirementId: string

    readonly branch?: string

    readonly budget?: number
}

/**
 * Request parameters for agentRetrievalServiceGraphCoverageGaps operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceGraphCoverageGapsRequest {
    readonly productId: string

    /**
     * requirement_ids is the set to check for coverage. Typically the result of RequirementImpact or RequirementNeighbors.
     */
    readonly requirementIds?: Array<string>
}

/**
 * Request parameters for agentRetrievalServiceListCoverageGaps operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceListCoverageGapsRequest {
    readonly productId: string

    readonly branch?: string

    readonly coverageStatuses?: Array<string>

    readonly componentId?: string

    readonly query?: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string

    /**
     * scope gaps to a feature subtree (root + descendants)
     */
    readonly rootRequirementId?: string
}

/**
 * Request parameters for agentRetrievalServiceListRequirementAnchors operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceListRequirementAnchorsRequest {
    readonly productId: string

    /**
     * empty &#x3D; main
     */
    readonly branch?: string
}

/**
 * Request parameters for agentRetrievalServicePrepareTestGenerationContext operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServicePrepareTestGenerationContextRequest {
    readonly productId: string

    readonly prepareTestGenerationContextBody: PrepareTestGenerationContextBody
}

/**
 * Request parameters for agentRetrievalServiceRequirementImpact operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceRequirementImpactRequest {
    readonly productId: string

    /**
     * repo_paths is the set of changed file paths (e.g. from a merged PR). The backend resolves these to seeded requirement IDs via requirement_sources.
     */
    readonly repoPaths?: Array<string>

    /**
     * depth controls how many hops the graph traversal expands beyond the seeds. Defaults to 3 on the server if &lt;&#x3D; 0.
     */
    readonly depth?: number

    /**
     * edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
     */
    readonly edgeTypes?: Array<string>
}

/**
 * Request parameters for agentRetrievalServiceRequirementNeighbors operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceRequirementNeighborsRequest {
    readonly productId: string

    readonly requirementId: string

    /**
     * depth controls how many hops to traverse (default 1 if &lt;&#x3D; 0).
     */
    readonly depth?: number

    /**
     * edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
     */
    readonly edgeTypes?: Array<string>
}

/**
 * Request parameters for agentRetrievalServiceResolveFeatureContext operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceResolveFeatureContextRequest {
    readonly productId: string

    /**
     * empty &#x3D; main
     */
    readonly branch?: string

    /**
     * text is the free-text coding objective to resolve into feature context.
     */
    readonly text?: string

    /**
     * repo_paths are optional changed file paths that seed anchor retrieval.
     */
    readonly repoPaths?: Array<string>

    /**
     * k bounds each retrieval signal\&#39;s breadth (server default when &lt;&#x3D; 0).
     */
    readonly k?: number
}

/**
 * Request parameters for agentRetrievalServiceWriteRequirementEdge operation in AgentRetrievalServiceApi.
 */
export interface AgentRetrievalServiceApiAgentRetrievalServiceWriteRequirementEdgeRequest {
    readonly productId: string

    readonly writeRequirementEdgeBody: WriteRequirementEdgeBody
}

/**
 * AgentRetrievalServiceApi - object-oriented interface
 */
export class AgentRetrievalServiceApi extends BaseAPI {
    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceAttributeChangedFilesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceAttributeChangedFiles(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceAttributeChangedFilesRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceAttributeChangedFiles(requestParameters.productId, requestParameters.requirementId, requestParameters.attributeChangedFilesBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceDeclareRequirementEdgeIntent(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceDeclareRequirementEdgeIntent(requestParameters.productId, requestParameters.declareRequirementEdgeIntentBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementGraphRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceGetRequirementGraph(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementGraphRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceGetRequirementGraph(requestParameters.productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementTestContextRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceGetRequirementTestContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGetRequirementTestContextRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceGetRequirementTestContext(requestParameters.productId, requestParameters.requirementId, requestParameters.branch, requestParameters.budget, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceGraphCoverageGapsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceGraphCoverageGaps(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceGraphCoverageGapsRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceGraphCoverageGaps(requestParameters.productId, requestParameters.requirementIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceListCoverageGapsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceListCoverageGaps(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceListCoverageGapsRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceListCoverageGaps(requestParameters.productId, requestParameters.branch, requestParameters.coverageStatuses, requestParameters.componentId, requestParameters.query, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.rootRequirementId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceListRequirementAnchorsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceListRequirementAnchors(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceListRequirementAnchorsRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceListRequirementAnchors(requestParameters.productId, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServicePrepareTestGenerationContextRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServicePrepareTestGenerationContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServicePrepareTestGenerationContextRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServicePrepareTestGenerationContext(requestParameters.productId, requestParameters.prepareTestGenerationContextBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceRequirementImpactRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceRequirementImpact(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceRequirementImpactRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceRequirementImpact(requestParameters.productId, requestParameters.repoPaths, requestParameters.depth, requestParameters.edgeTypes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceRequirementNeighborsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceRequirementNeighbors(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceRequirementNeighborsRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceRequirementNeighbors(requestParameters.productId, requestParameters.requirementId, requestParameters.depth, requestParameters.edgeTypes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceResolveFeatureContextRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceResolveFeatureContext(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceResolveFeatureContextRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceResolveFeatureContext(requestParameters.productId, requestParameters.branch, requestParameters.text, requestParameters.repoPaths, requestParameters.k, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRetrievalServiceApiAgentRetrievalServiceWriteRequirementEdgeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRetrievalServiceWriteRequirementEdge(requestParameters: AgentRetrievalServiceApiAgentRetrievalServiceWriteRequirementEdgeRequest, options?: RawAxiosRequestConfig) {
        return AgentRetrievalServiceApiFp(this.configuration).agentRetrievalServiceWriteRequirementEdge(requestParameters.productId, requestParameters.writeRequirementEdgeBody, options).then((request) => request(this.axios, this.basePath));
    }
}

