/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CancelAgentRunBody } from '../model';
// @ts-ignore
import type { CancelAgentRunResponse } from '../model';
// @ts-ignore
import type { GetAgentRunResponse } from '../model';
// @ts-ignore
import type { ListAgentRunEventsResponse } from '../model';
// @ts-ignore
import type { ListAgentRunsResponse } from '../model';
// @ts-ignore
import type { StartAgentRunBody } from '../model';
// @ts-ignore
import type { StartAgentRunResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { StreamResultOfAgentRunEvent } from '../model';
/**
 * AgentRunServiceApi - axios parameter creator
 */
export const AgentRunServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {CancelAgentRunBody} cancelAgentRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceCancelAgentRun: async (id: string, cancelAgentRunBody: CancelAgentRunBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('agentRunServiceCancelAgentRun', 'id', id)
            // verify required parameter 'cancelAgentRunBody' is not null or undefined
            assertParamExists('agentRunServiceCancelAgentRun', 'cancelAgentRunBody', cancelAgentRunBody)
            const localVarPath = `/v1/agent-runs/{id}:cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelAgentRunBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceGetAgentRun: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('agentRunServiceGetAgentRun', 'id', id)
            const localVarPath = `/v1/agent-runs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} runId 
         * @param {number} [pageSize] 
         * @param {string} [pageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceListAgentRunEvents: async (runId: string, pageSize?: number, pageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            assertParamExists('agentRunServiceListAgentRunEvents', 'runId', runId)
            const localVarPath = `/v1/agent-runs/{runId}/events`
                .replace(`{${"runId"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['pageToken'] = pageToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} agentConfigId 
         * @param {number} [pageSize] 
         * @param {string} [pageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceListAgentRuns: async (agentConfigId: string, pageSize?: number, pageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentConfigId' is not null or undefined
            assertParamExists('agentRunServiceListAgentRuns', 'agentConfigId', agentConfigId)
            const localVarPath = `/v1/agent-configs/{agentConfigId}/runs`
                .replace(`{${"agentConfigId"}}`, encodeURIComponent(String(agentConfigId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['pageToken'] = pageToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} agentConfigId 
         * @param {StartAgentRunBody} startAgentRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceStartAgentRun: async (agentConfigId: string, startAgentRunBody: StartAgentRunBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentConfigId' is not null or undefined
            assertParamExists('agentRunServiceStartAgentRun', 'agentConfigId', agentConfigId)
            // verify required parameter 'startAgentRunBody' is not null or undefined
            assertParamExists('agentRunServiceStartAgentRun', 'startAgentRunBody', startAgentRunBody)
            const localVarPath = `/v1/agent-configs/{agentConfigId}/runs`
                .replace(`{${"agentConfigId"}}`, encodeURIComponent(String(agentConfigId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(startAgentRunBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} runId 
         * @param {string} [afterEventId] resume from this event id (cursor); empty starts from the beginning.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceStreamAgentRun: async (runId: string, afterEventId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            assertParamExists('agentRunServiceStreamAgentRun', 'runId', runId)
            const localVarPath = `/v1/agent-runs/{runId}/events:stream`
                .replace(`{${"runId"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (afterEventId !== undefined) {
                localVarQueryParameter['afterEventId'] = afterEventId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgentRunServiceApi - functional programming interface
 */
export const AgentRunServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AgentRunServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {CancelAgentRunBody} cancelAgentRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceCancelAgentRun(id: string, cancelAgentRunBody: CancelAgentRunBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelAgentRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceCancelAgentRun(id, cancelAgentRunBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceCancelAgentRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceGetAgentRun(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAgentRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceGetAgentRun(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceGetAgentRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} runId 
         * @param {number} [pageSize] 
         * @param {string} [pageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceListAgentRunEvents(runId: string, pageSize?: number, pageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListAgentRunEventsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceListAgentRunEvents(runId, pageSize, pageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceListAgentRunEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} agentConfigId 
         * @param {number} [pageSize] 
         * @param {string} [pageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceListAgentRuns(agentConfigId: string, pageSize?: number, pageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListAgentRunsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceListAgentRuns(agentConfigId, pageSize, pageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceListAgentRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} agentConfigId 
         * @param {StartAgentRunBody} startAgentRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceStartAgentRun(agentConfigId: string, startAgentRunBody: StartAgentRunBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartAgentRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceStartAgentRun(agentConfigId, startAgentRunBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceStartAgentRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} runId 
         * @param {string} [afterEventId] resume from this event id (cursor); empty starts from the beginning.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentRunServiceStreamAgentRun(runId: string, afterEventId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StreamResultOfAgentRunEvent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentRunServiceStreamAgentRun(runId, afterEventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentRunServiceApi.agentRunServiceStreamAgentRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AgentRunServiceApi - factory interface
 */
export const AgentRunServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AgentRunServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceCancelAgentRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceCancelAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceCancelAgentRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<CancelAgentRunResponse> {
            return localVarFp.agentRunServiceCancelAgentRun(requestParameters.id, requestParameters.cancelAgentRunBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceGetAgentRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceGetAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceGetAgentRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetAgentRunResponse> {
            return localVarFp.agentRunServiceGetAgentRun(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceListAgentRunEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceListAgentRunEvents(requestParameters: AgentRunServiceApiAgentRunServiceListAgentRunEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListAgentRunEventsResponse> {
            return localVarFp.agentRunServiceListAgentRunEvents(requestParameters.runId, requestParameters.pageSize, requestParameters.pageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceListAgentRunsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceListAgentRuns(requestParameters: AgentRunServiceApiAgentRunServiceListAgentRunsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListAgentRunsResponse> {
            return localVarFp.agentRunServiceListAgentRuns(requestParameters.agentConfigId, requestParameters.pageSize, requestParameters.pageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceStartAgentRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceStartAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceStartAgentRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<StartAgentRunResponse> {
            return localVarFp.agentRunServiceStartAgentRun(requestParameters.agentConfigId, requestParameters.startAgentRunBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AgentRunServiceApiAgentRunServiceStreamAgentRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentRunServiceStreamAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceStreamAgentRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<StreamResultOfAgentRunEvent> {
            return localVarFp.agentRunServiceStreamAgentRun(requestParameters.runId, requestParameters.afterEventId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for agentRunServiceCancelAgentRun operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceCancelAgentRunRequest {
    readonly id: string

    readonly cancelAgentRunBody: CancelAgentRunBody
}

/**
 * Request parameters for agentRunServiceGetAgentRun operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceGetAgentRunRequest {
    readonly id: string
}

/**
 * Request parameters for agentRunServiceListAgentRunEvents operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceListAgentRunEventsRequest {
    readonly runId: string

    readonly pageSize?: number

    readonly pageToken?: string
}

/**
 * Request parameters for agentRunServiceListAgentRuns operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceListAgentRunsRequest {
    readonly agentConfigId: string

    readonly pageSize?: number

    readonly pageToken?: string
}

/**
 * Request parameters for agentRunServiceStartAgentRun operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceStartAgentRunRequest {
    readonly agentConfigId: string

    readonly startAgentRunBody: StartAgentRunBody
}

/**
 * Request parameters for agentRunServiceStreamAgentRun operation in AgentRunServiceApi.
 */
export interface AgentRunServiceApiAgentRunServiceStreamAgentRunRequest {
    readonly runId: string

    /**
     * resume from this event id (cursor); empty starts from the beginning.
     */
    readonly afterEventId?: string
}

/**
 * AgentRunServiceApi - object-oriented interface
 */
export class AgentRunServiceApi extends BaseAPI {
    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceCancelAgentRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceCancelAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceCancelAgentRunRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceCancelAgentRun(requestParameters.id, requestParameters.cancelAgentRunBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceGetAgentRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceGetAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceGetAgentRunRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceGetAgentRun(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceListAgentRunEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceListAgentRunEvents(requestParameters: AgentRunServiceApiAgentRunServiceListAgentRunEventsRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceListAgentRunEvents(requestParameters.runId, requestParameters.pageSize, requestParameters.pageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceListAgentRunsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceListAgentRuns(requestParameters: AgentRunServiceApiAgentRunServiceListAgentRunsRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceListAgentRuns(requestParameters.agentConfigId, requestParameters.pageSize, requestParameters.pageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceStartAgentRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceStartAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceStartAgentRunRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceStartAgentRun(requestParameters.agentConfigId, requestParameters.startAgentRunBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AgentRunServiceApiAgentRunServiceStreamAgentRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentRunServiceStreamAgentRun(requestParameters: AgentRunServiceApiAgentRunServiceStreamAgentRunRequest, options?: RawAxiosRequestConfig) {
        return AgentRunServiceApiFp(this.configuration).agentRunServiceStreamAgentRun(requestParameters.runId, requestParameters.afterEventId, options).then((request) => request(this.axios, this.basePath));
    }
}

