/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateBranchBody } from '../model';
// @ts-ignore
import type { CreateBranchResponse } from '../model';
// @ts-ignore
import type { GetBranchResponse } from '../model';
// @ts-ignore
import type { GetMergePreviewResponse } from '../model';
// @ts-ignore
import type { ListBranchCodeLinksResponse } from '../model';
// @ts-ignore
import type { ListBranchesResponse } from '../model';
// @ts-ignore
import type { MergeBranchBody } from '../model';
// @ts-ignore
import type { MergeBranchResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { UpdateBranchBody } from '../model';
// @ts-ignore
import type { UpdateBranchResponse } from '../model';
// @ts-ignore
import type { UpsertBranchCodeLinksBody } from '../model';
// @ts-ignore
import type { UpsertBranchCodeLinksResponse } from '../model';
/**
 * BranchServiceApi - axios parameter creator
 */
export const BranchServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The branch starts as a view of main; edits made on it copy entities on write and flow back via MergeBranch. name must be lowercase alphanumeric with hyphens/underscores/slashes, at most 100 characters, and not \"main\". created_by_agent_run_id attributes branches created by an agent run.
         * @summary Creates a copy-on-write branch of a product\'s main line.
         * @param {string} productId 
         * @param {CreateBranchBody} createBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceCreateBranch: async (productId: string, createBranchBody: CreateBranchBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('branchServiceCreateBranch', 'productId', productId)
            // verify required parameter 'createBranchBody' is not null or undefined
            assertParamExists('branchServiceCreateBranch', 'createBranchBody', createBranchBody)
            const localVarPath = `/v1/products/{productId}/branches`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBranchBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permanently drops the branch\'s local requirement/test/component copies and deletion markers; main is unaffected. Deletion history is recorded per discarded requirement. The main branch cannot be deleted.
         * @summary Deletes a branch and discards its copy-on-write changes.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceDeleteBranch: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('branchServiceDeleteBranch', 'id', id)
            const localVarPath = `/v1/branches/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the branch with its status and metadata. Change stats are only populated by ListBranches with include_stats=true.
         * @summary Fetches one branch by id.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceGetBranch: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('branchServiceGetBranch', 'id', id)
            const localVarPath = `/v1/branches/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the additions, modifications (with per-field conflict flags), and deletions the merge would apply, for requirements, tests, and components, plus aggregate stats. A conflict means main changed the entity after the branch took its copy. Read-only — nothing is written.
         * @summary Previews the effect of merging a branch into main.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceGetMergePreview: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('branchServiceGetMergePreview', 'id', id)
            const localVarPath = `/v1/branches/{id}/merge-preview`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns every link recorded for the branch, pull requests before git branches, then most recently updated first.
         * @summary Lists a branch\'s durable code links (git branches, pull requests).
         * @param {string} branchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceListBranchCodeLinks: async (branchId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'branchId' is not null or undefined
            assertParamExists('branchServiceListBranchCodeLinks', 'branchId', branchId)
            const localVarPath = `/v1/branches/{branchId}/code-links`
                .replace(`{${"branchId"}}`, encodeURIComponent(String(branchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns every branch including main. Set include_stats to add per-branch change counts vs main (additions/modifications/deletions per entity kind, plus conflicts). Set include_status to add loop/latest-run/code-link/ intent-capture signals (Branch.loop/.latest_run/.code_links/.intent) — independent of include_stats, each is its own fixed-query-count batch read, so a caller that needs only the branch list is not charged for it.
         * @summary Lists a product\'s branches.
         * @param {string} productId 
         * @param {boolean} [includeStats] When true, each returned Branch carries BranchChangeStats (per-branch change counts vs main).
         * @param {boolean} [includeStatus] When true, each returned Branch carries loop/latest-run/code-link/intent status signals (Branch.loop, .latest_run, .code_links, .intent). Kept separate from include_stats: the sidebar branch dropdown calls List without stats and must not pay for this extra work either.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceListBranches: async (productId: string, includeStats?: boolean, includeStatus?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('branchServiceListBranches', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/branches`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (includeStats !== undefined) {
                localVarQueryParameter['includeStats'] = includeStats;
            }

            if (includeStatus !== undefined) {
                localVarQueryParameter['includeStatus'] = includeStatus;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Applies the branch\'s additions/modifications/deletions to main in one transaction. Every conflicting entity requires a resolutions entry keyed \"req:<uuid>\", \"test:<uuid>\", or \"comp:<uuid>\" with value KEEP_BRANCH or KEEP_MAIN — otherwise the call fails with UNRESOLVED_CONFLICT and nothing is applied. Only open branches can merge; main cannot merge into itself.
         * @summary Merges a branch\'s changes into main and closes the branch.
         * @param {string} id 
         * @param {MergeBranchBody} mergeBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceMergeBranch: async (id: string, mergeBranchBody: MergeBranchBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('branchServiceMergeBranch', 'id', id)
            // verify required parameter 'mergeBranchBody' is not null or undefined
            assertParamExists('branchServiceMergeBranch', 'mergeBranchBody', mergeBranchBody)
            const localVarPath = `/v1/branches/{id}/merge`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mergeBranchBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Both request fields are optional: an absent field leaves the branch\'s current value unchanged, a present field (including an empty string) sets it. created_by_agent is validated server-side against a fixed allowlist — an unrecognized value is stored as empty string.
         * @summary Updates a branch\'s description and/or created_by_agent.
         * @param {string} id 
         * @param {UpdateBranchBody} updateBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceUpdateBranch: async (id: string, updateBranchBody: UpdateBranchBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('branchServiceUpdateBranch', 'id', id)
            // verify required parameter 'updateBranchBody' is not null or undefined
            assertParamExists('branchServiceUpdateBranch', 'updateBranchBody', updateBranchBody)
            const localVarPath = `/v1/branches/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBranchBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Each entry is keyed by (kind, repository, ref): a repeat of an existing key updates url/title/state/base_sha/head_sha instead of duplicating. kind must be \"git_branch\" or \"pull_request\"; state must be \"\", \"open\", \"merged\", or \"closed\". Fails closed on the first invalid entry — nothing is written if any entry is invalid.
         * @summary Upserts a batch of code links onto a branch.
         * @param {string} branchId 
         * @param {UpsertBranchCodeLinksBody} upsertBranchCodeLinksBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceUpsertBranchCodeLinks: async (branchId: string, upsertBranchCodeLinksBody: UpsertBranchCodeLinksBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'branchId' is not null or undefined
            assertParamExists('branchServiceUpsertBranchCodeLinks', 'branchId', branchId)
            // verify required parameter 'upsertBranchCodeLinksBody' is not null or undefined
            assertParamExists('branchServiceUpsertBranchCodeLinks', 'upsertBranchCodeLinksBody', upsertBranchCodeLinksBody)
            const localVarPath = `/v1/branches/{branchId}/code-links`
                .replace(`{${"branchId"}}`, encodeURIComponent(String(branchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertBranchCodeLinksBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BranchServiceApi - functional programming interface
 */
export const BranchServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BranchServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * The branch starts as a view of main; edits made on it copy entities on write and flow back via MergeBranch. name must be lowercase alphanumeric with hyphens/underscores/slashes, at most 100 characters, and not \"main\". created_by_agent_run_id attributes branches created by an agent run.
         * @summary Creates a copy-on-write branch of a product\'s main line.
         * @param {string} productId 
         * @param {CreateBranchBody} createBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceCreateBranch(productId: string, createBranchBody: CreateBranchBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateBranchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceCreateBranch(productId, createBranchBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceCreateBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permanently drops the branch\'s local requirement/test/component copies and deletion markers; main is unaffected. Deletion history is recorded per discarded requirement. The main branch cannot be deleted.
         * @summary Deletes a branch and discards its copy-on-write changes.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceDeleteBranch(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceDeleteBranch(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceDeleteBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the branch with its status and metadata. Change stats are only populated by ListBranches with include_stats=true.
         * @summary Fetches one branch by id.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceGetBranch(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetBranchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceGetBranch(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceGetBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the additions, modifications (with per-field conflict flags), and deletions the merge would apply, for requirements, tests, and components, plus aggregate stats. A conflict means main changed the entity after the branch took its copy. Read-only — nothing is written.
         * @summary Previews the effect of merging a branch into main.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceGetMergePreview(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMergePreviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceGetMergePreview(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceGetMergePreview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns every link recorded for the branch, pull requests before git branches, then most recently updated first.
         * @summary Lists a branch\'s durable code links (git branches, pull requests).
         * @param {string} branchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceListBranchCodeLinks(branchId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBranchCodeLinksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceListBranchCodeLinks(branchId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceListBranchCodeLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns every branch including main. Set include_stats to add per-branch change counts vs main (additions/modifications/deletions per entity kind, plus conflicts). Set include_status to add loop/latest-run/code-link/ intent-capture signals (Branch.loop/.latest_run/.code_links/.intent) — independent of include_stats, each is its own fixed-query-count batch read, so a caller that needs only the branch list is not charged for it.
         * @summary Lists a product\'s branches.
         * @param {string} productId 
         * @param {boolean} [includeStats] When true, each returned Branch carries BranchChangeStats (per-branch change counts vs main).
         * @param {boolean} [includeStatus] When true, each returned Branch carries loop/latest-run/code-link/intent status signals (Branch.loop, .latest_run, .code_links, .intent). Kept separate from include_stats: the sidebar branch dropdown calls List without stats and must not pay for this extra work either.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceListBranches(productId: string, includeStats?: boolean, includeStatus?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBranchesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceListBranches(productId, includeStats, includeStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceListBranches']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Applies the branch\'s additions/modifications/deletions to main in one transaction. Every conflicting entity requires a resolutions entry keyed \"req:<uuid>\", \"test:<uuid>\", or \"comp:<uuid>\" with value KEEP_BRANCH or KEEP_MAIN — otherwise the call fails with UNRESOLVED_CONFLICT and nothing is applied. Only open branches can merge; main cannot merge into itself.
         * @summary Merges a branch\'s changes into main and closes the branch.
         * @param {string} id 
         * @param {MergeBranchBody} mergeBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceMergeBranch(id: string, mergeBranchBody: MergeBranchBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MergeBranchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceMergeBranch(id, mergeBranchBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceMergeBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Both request fields are optional: an absent field leaves the branch\'s current value unchanged, a present field (including an empty string) sets it. created_by_agent is validated server-side against a fixed allowlist — an unrecognized value is stored as empty string.
         * @summary Updates a branch\'s description and/or created_by_agent.
         * @param {string} id 
         * @param {UpdateBranchBody} updateBranchBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceUpdateBranch(id: string, updateBranchBody: UpdateBranchBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateBranchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceUpdateBranch(id, updateBranchBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceUpdateBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Each entry is keyed by (kind, repository, ref): a repeat of an existing key updates url/title/state/base_sha/head_sha instead of duplicating. kind must be \"git_branch\" or \"pull_request\"; state must be \"\", \"open\", \"merged\", or \"closed\". Fails closed on the first invalid entry — nothing is written if any entry is invalid.
         * @summary Upserts a batch of code links onto a branch.
         * @param {string} branchId 
         * @param {UpsertBranchCodeLinksBody} upsertBranchCodeLinksBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchServiceUpsertBranchCodeLinks(branchId: string, upsertBranchCodeLinksBody: UpsertBranchCodeLinksBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpsertBranchCodeLinksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchServiceUpsertBranchCodeLinks(branchId, upsertBranchCodeLinksBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchServiceApi.branchServiceUpsertBranchCodeLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BranchServiceApi - factory interface
 */
export const BranchServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BranchServiceApiFp(configuration)
    return {
        /**
         * The branch starts as a view of main; edits made on it copy entities on write and flow back via MergeBranch. name must be lowercase alphanumeric with hyphens/underscores/slashes, at most 100 characters, and not \"main\". created_by_agent_run_id attributes branches created by an agent run.
         * @summary Creates a copy-on-write branch of a product\'s main line.
         * @param {BranchServiceApiBranchServiceCreateBranchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceCreateBranch(requestParameters: BranchServiceApiBranchServiceCreateBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateBranchResponse> {
            return localVarFp.branchServiceCreateBranch(requestParameters.productId, requestParameters.createBranchBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Permanently drops the branch\'s local requirement/test/component copies and deletion markers; main is unaffected. Deletion history is recorded per discarded requirement. The main branch cannot be deleted.
         * @summary Deletes a branch and discards its copy-on-write changes.
         * @param {BranchServiceApiBranchServiceDeleteBranchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceDeleteBranch(requestParameters: BranchServiceApiBranchServiceDeleteBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.branchServiceDeleteBranch(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the branch with its status and metadata. Change stats are only populated by ListBranches with include_stats=true.
         * @summary Fetches one branch by id.
         * @param {BranchServiceApiBranchServiceGetBranchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceGetBranch(requestParameters: BranchServiceApiBranchServiceGetBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetBranchResponse> {
            return localVarFp.branchServiceGetBranch(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the additions, modifications (with per-field conflict flags), and deletions the merge would apply, for requirements, tests, and components, plus aggregate stats. A conflict means main changed the entity after the branch took its copy. Read-only — nothing is written.
         * @summary Previews the effect of merging a branch into main.
         * @param {BranchServiceApiBranchServiceGetMergePreviewRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceGetMergePreview(requestParameters: BranchServiceApiBranchServiceGetMergePreviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetMergePreviewResponse> {
            return localVarFp.branchServiceGetMergePreview(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns every link recorded for the branch, pull requests before git branches, then most recently updated first.
         * @summary Lists a branch\'s durable code links (git branches, pull requests).
         * @param {BranchServiceApiBranchServiceListBranchCodeLinksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceListBranchCodeLinks(requestParameters: BranchServiceApiBranchServiceListBranchCodeLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListBranchCodeLinksResponse> {
            return localVarFp.branchServiceListBranchCodeLinks(requestParameters.branchId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns every branch including main. Set include_stats to add per-branch change counts vs main (additions/modifications/deletions per entity kind, plus conflicts). Set include_status to add loop/latest-run/code-link/ intent-capture signals (Branch.loop/.latest_run/.code_links/.intent) — independent of include_stats, each is its own fixed-query-count batch read, so a caller that needs only the branch list is not charged for it.
         * @summary Lists a product\'s branches.
         * @param {BranchServiceApiBranchServiceListBranchesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceListBranches(requestParameters: BranchServiceApiBranchServiceListBranchesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListBranchesResponse> {
            return localVarFp.branchServiceListBranches(requestParameters.productId, requestParameters.includeStats, requestParameters.includeStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * Applies the branch\'s additions/modifications/deletions to main in one transaction. Every conflicting entity requires a resolutions entry keyed \"req:<uuid>\", \"test:<uuid>\", or \"comp:<uuid>\" with value KEEP_BRANCH or KEEP_MAIN — otherwise the call fails with UNRESOLVED_CONFLICT and nothing is applied. Only open branches can merge; main cannot merge into itself.
         * @summary Merges a branch\'s changes into main and closes the branch.
         * @param {BranchServiceApiBranchServiceMergeBranchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceMergeBranch(requestParameters: BranchServiceApiBranchServiceMergeBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<MergeBranchResponse> {
            return localVarFp.branchServiceMergeBranch(requestParameters.id, requestParameters.mergeBranchBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Both request fields are optional: an absent field leaves the branch\'s current value unchanged, a present field (including an empty string) sets it. created_by_agent is validated server-side against a fixed allowlist — an unrecognized value is stored as empty string.
         * @summary Updates a branch\'s description and/or created_by_agent.
         * @param {BranchServiceApiBranchServiceUpdateBranchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceUpdateBranch(requestParameters: BranchServiceApiBranchServiceUpdateBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateBranchResponse> {
            return localVarFp.branchServiceUpdateBranch(requestParameters.id, requestParameters.updateBranchBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Each entry is keyed by (kind, repository, ref): a repeat of an existing key updates url/title/state/base_sha/head_sha instead of duplicating. kind must be \"git_branch\" or \"pull_request\"; state must be \"\", \"open\", \"merged\", or \"closed\". Fails closed on the first invalid entry — nothing is written if any entry is invalid.
         * @summary Upserts a batch of code links onto a branch.
         * @param {BranchServiceApiBranchServiceUpsertBranchCodeLinksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchServiceUpsertBranchCodeLinks(requestParameters: BranchServiceApiBranchServiceUpsertBranchCodeLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpsertBranchCodeLinksResponse> {
            return localVarFp.branchServiceUpsertBranchCodeLinks(requestParameters.branchId, requestParameters.upsertBranchCodeLinksBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for branchServiceCreateBranch operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceCreateBranchRequest {
    readonly productId: string

    readonly createBranchBody: CreateBranchBody
}

/**
 * Request parameters for branchServiceDeleteBranch operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceDeleteBranchRequest {
    readonly id: string
}

/**
 * Request parameters for branchServiceGetBranch operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceGetBranchRequest {
    readonly id: string
}

/**
 * Request parameters for branchServiceGetMergePreview operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceGetMergePreviewRequest {
    readonly id: string
}

/**
 * Request parameters for branchServiceListBranchCodeLinks operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceListBranchCodeLinksRequest {
    readonly branchId: string
}

/**
 * Request parameters for branchServiceListBranches operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceListBranchesRequest {
    readonly productId: string

    /**
     * When true, each returned Branch carries BranchChangeStats (per-branch change counts vs main).
     */
    readonly includeStats?: boolean

    /**
     * When true, each returned Branch carries loop/latest-run/code-link/intent status signals (Branch.loop, .latest_run, .code_links, .intent). Kept separate from include_stats: the sidebar branch dropdown calls List without stats and must not pay for this extra work either.
     */
    readonly includeStatus?: boolean
}

/**
 * Request parameters for branchServiceMergeBranch operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceMergeBranchRequest {
    readonly id: string

    readonly mergeBranchBody: MergeBranchBody
}

/**
 * Request parameters for branchServiceUpdateBranch operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceUpdateBranchRequest {
    readonly id: string

    readonly updateBranchBody: UpdateBranchBody
}

/**
 * Request parameters for branchServiceUpsertBranchCodeLinks operation in BranchServiceApi.
 */
export interface BranchServiceApiBranchServiceUpsertBranchCodeLinksRequest {
    readonly branchId: string

    readonly upsertBranchCodeLinksBody: UpsertBranchCodeLinksBody
}

/**
 * BranchServiceApi - object-oriented interface
 */
export class BranchServiceApi extends BaseAPI {
    /**
     * The branch starts as a view of main; edits made on it copy entities on write and flow back via MergeBranch. name must be lowercase alphanumeric with hyphens/underscores/slashes, at most 100 characters, and not \"main\". created_by_agent_run_id attributes branches created by an agent run.
     * @summary Creates a copy-on-write branch of a product\'s main line.
     * @param {BranchServiceApiBranchServiceCreateBranchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceCreateBranch(requestParameters: BranchServiceApiBranchServiceCreateBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceCreateBranch(requestParameters.productId, requestParameters.createBranchBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permanently drops the branch\'s local requirement/test/component copies and deletion markers; main is unaffected. Deletion history is recorded per discarded requirement. The main branch cannot be deleted.
     * @summary Deletes a branch and discards its copy-on-write changes.
     * @param {BranchServiceApiBranchServiceDeleteBranchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceDeleteBranch(requestParameters: BranchServiceApiBranchServiceDeleteBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceDeleteBranch(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the branch with its status and metadata. Change stats are only populated by ListBranches with include_stats=true.
     * @summary Fetches one branch by id.
     * @param {BranchServiceApiBranchServiceGetBranchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceGetBranch(requestParameters: BranchServiceApiBranchServiceGetBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceGetBranch(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the additions, modifications (with per-field conflict flags), and deletions the merge would apply, for requirements, tests, and components, plus aggregate stats. A conflict means main changed the entity after the branch took its copy. Read-only — nothing is written.
     * @summary Previews the effect of merging a branch into main.
     * @param {BranchServiceApiBranchServiceGetMergePreviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceGetMergePreview(requestParameters: BranchServiceApiBranchServiceGetMergePreviewRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceGetMergePreview(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns every link recorded for the branch, pull requests before git branches, then most recently updated first.
     * @summary Lists a branch\'s durable code links (git branches, pull requests).
     * @param {BranchServiceApiBranchServiceListBranchCodeLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceListBranchCodeLinks(requestParameters: BranchServiceApiBranchServiceListBranchCodeLinksRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceListBranchCodeLinks(requestParameters.branchId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns every branch including main. Set include_stats to add per-branch change counts vs main (additions/modifications/deletions per entity kind, plus conflicts). Set include_status to add loop/latest-run/code-link/ intent-capture signals (Branch.loop/.latest_run/.code_links/.intent) — independent of include_stats, each is its own fixed-query-count batch read, so a caller that needs only the branch list is not charged for it.
     * @summary Lists a product\'s branches.
     * @param {BranchServiceApiBranchServiceListBranchesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceListBranches(requestParameters: BranchServiceApiBranchServiceListBranchesRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceListBranches(requestParameters.productId, requestParameters.includeStats, requestParameters.includeStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Applies the branch\'s additions/modifications/deletions to main in one transaction. Every conflicting entity requires a resolutions entry keyed \"req:<uuid>\", \"test:<uuid>\", or \"comp:<uuid>\" with value KEEP_BRANCH or KEEP_MAIN — otherwise the call fails with UNRESOLVED_CONFLICT and nothing is applied. Only open branches can merge; main cannot merge into itself.
     * @summary Merges a branch\'s changes into main and closes the branch.
     * @param {BranchServiceApiBranchServiceMergeBranchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceMergeBranch(requestParameters: BranchServiceApiBranchServiceMergeBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceMergeBranch(requestParameters.id, requestParameters.mergeBranchBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Both request fields are optional: an absent field leaves the branch\'s current value unchanged, a present field (including an empty string) sets it. created_by_agent is validated server-side against a fixed allowlist — an unrecognized value is stored as empty string.
     * @summary Updates a branch\'s description and/or created_by_agent.
     * @param {BranchServiceApiBranchServiceUpdateBranchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceUpdateBranch(requestParameters: BranchServiceApiBranchServiceUpdateBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceUpdateBranch(requestParameters.id, requestParameters.updateBranchBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Each entry is keyed by (kind, repository, ref): a repeat of an existing key updates url/title/state/base_sha/head_sha instead of duplicating. kind must be \"git_branch\" or \"pull_request\"; state must be \"\", \"open\", \"merged\", or \"closed\". Fails closed on the first invalid entry — nothing is written if any entry is invalid.
     * @summary Upserts a batch of code links onto a branch.
     * @param {BranchServiceApiBranchServiceUpsertBranchCodeLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public branchServiceUpsertBranchCodeLinks(requestParameters: BranchServiceApiBranchServiceUpsertBranchCodeLinksRequest, options?: RawAxiosRequestConfig) {
        return BranchServiceApiFp(this.configuration).branchServiceUpsertBranchCodeLinks(requestParameters.branchId, requestParameters.upsertBranchCodeLinksBody, options).then((request) => request(this.axios, this.basePath));
    }
}

