/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateComponentBody } from '../model';
// @ts-ignore
import type { CreateComponentResponse } from '../model';
// @ts-ignore
import type { ListComponentsResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { UpdateComponentBody } from '../model';
// @ts-ignore
import type { UpdateComponentResponse } from '../model';
/**
 * ComponentServiceApi - axios parameter creator
 */
export const ComponentServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productId 
         * @param {CreateComponentBody} createComponentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceCreateComponent: async (productId: string, createComponentBody: CreateComponentBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('componentServiceCreateComponent', 'productId', productId)
            // verify required parameter 'createComponentBody' is not null or undefined
            assertParamExists('componentServiceCreateComponent', 'createComponentBody', createComponentBody)
            const localVarPath = `/v1/products/{productId}/components`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createComponentBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceListComponents: async (productId: string, paginationPageSize?: number, paginationPageToken?: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('componentServiceListComponents', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/components`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateComponentBody} updateComponentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceUpdateComponent: async (id: string, updateComponentBody: UpdateComponentBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('componentServiceUpdateComponent', 'id', id)
            // verify required parameter 'updateComponentBody' is not null or undefined
            assertParamExists('componentServiceUpdateComponent', 'updateComponentBody', updateComponentBody)
            const localVarPath = `/v1/components/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateComponentBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ComponentServiceApi - functional programming interface
 */
export const ComponentServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ComponentServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productId 
         * @param {CreateComponentBody} createComponentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async componentServiceCreateComponent(productId: string, createComponentBody: CreateComponentBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateComponentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.componentServiceCreateComponent(productId, createComponentBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComponentServiceApi.componentServiceCreateComponent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async componentServiceListComponents(productId: string, paginationPageSize?: number, paginationPageToken?: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListComponentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.componentServiceListComponents(productId, paginationPageSize, paginationPageToken, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComponentServiceApi.componentServiceListComponents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateComponentBody} updateComponentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async componentServiceUpdateComponent(id: string, updateComponentBody: UpdateComponentBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateComponentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.componentServiceUpdateComponent(id, updateComponentBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ComponentServiceApi.componentServiceUpdateComponent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ComponentServiceApi - factory interface
 */
export const ComponentServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ComponentServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ComponentServiceApiComponentServiceCreateComponentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceCreateComponent(requestParameters: ComponentServiceApiComponentServiceCreateComponentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateComponentResponse> {
            return localVarFp.componentServiceCreateComponent(requestParameters.productId, requestParameters.createComponentBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ComponentServiceApiComponentServiceListComponentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceListComponents(requestParameters: ComponentServiceApiComponentServiceListComponentsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListComponentsResponse> {
            return localVarFp.componentServiceListComponents(requestParameters.productId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ComponentServiceApiComponentServiceUpdateComponentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        componentServiceUpdateComponent(requestParameters: ComponentServiceApiComponentServiceUpdateComponentRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateComponentResponse> {
            return localVarFp.componentServiceUpdateComponent(requestParameters.id, requestParameters.updateComponentBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for componentServiceCreateComponent operation in ComponentServiceApi.
 */
export interface ComponentServiceApiComponentServiceCreateComponentRequest {
    readonly productId: string

    readonly createComponentBody: CreateComponentBody
}

/**
 * Request parameters for componentServiceListComponents operation in ComponentServiceApi.
 */
export interface ComponentServiceApiComponentServiceListComponentsRequest {
    readonly productId: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string

    readonly branch?: string
}

/**
 * Request parameters for componentServiceUpdateComponent operation in ComponentServiceApi.
 */
export interface ComponentServiceApiComponentServiceUpdateComponentRequest {
    readonly id: string

    readonly updateComponentBody: UpdateComponentBody
}

/**
 * ComponentServiceApi - object-oriented interface
 */
export class ComponentServiceApi extends BaseAPI {
    /**
     * 
     * @param {ComponentServiceApiComponentServiceCreateComponentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public componentServiceCreateComponent(requestParameters: ComponentServiceApiComponentServiceCreateComponentRequest, options?: RawAxiosRequestConfig) {
        return ComponentServiceApiFp(this.configuration).componentServiceCreateComponent(requestParameters.productId, requestParameters.createComponentBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ComponentServiceApiComponentServiceListComponentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public componentServiceListComponents(requestParameters: ComponentServiceApiComponentServiceListComponentsRequest, options?: RawAxiosRequestConfig) {
        return ComponentServiceApiFp(this.configuration).componentServiceListComponents(requestParameters.productId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ComponentServiceApiComponentServiceUpdateComponentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public componentServiceUpdateComponent(requestParameters: ComponentServiceApiComponentServiceUpdateComponentRequest, options?: RawAxiosRequestConfig) {
        return ComponentServiceApiFp(this.configuration).componentServiceUpdateComponent(requestParameters.id, requestParameters.updateComponentBody, options).then((request) => request(this.axios, this.basePath));
    }
}

