/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DistillIntentBody } from '../model';
// @ts-ignore
import type { DistillIntentResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
/**
 * IntentServiceApi - axios parameter creator
 */
export const IntentServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productId Product whose requirement tree the intent is reconciled against.
         * @param {DistillIntentBody} distillIntentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentServiceDistillIntent: async (productId: string, distillIntentBody: DistillIntentBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('intentServiceDistillIntent', 'productId', productId)
            // verify required parameter 'distillIntentBody' is not null or undefined
            assertParamExists('intentServiceDistillIntent', 'distillIntentBody', distillIntentBody)
            const localVarPath = `/v1/products/{productId}/intent:distill`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(distillIntentBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IntentServiceApi - functional programming interface
 */
export const IntentServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IntentServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productId Product whose requirement tree the intent is reconciled against.
         * @param {DistillIntentBody} distillIntentBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intentServiceDistillIntent(productId: string, distillIntentBody: DistillIntentBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DistillIntentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intentServiceDistillIntent(productId, distillIntentBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IntentServiceApi.intentServiceDistillIntent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IntentServiceApi - factory interface
 */
export const IntentServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IntentServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IntentServiceApiIntentServiceDistillIntentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentServiceDistillIntent(requestParameters: IntentServiceApiIntentServiceDistillIntentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DistillIntentResponse> {
            return localVarFp.intentServiceDistillIntent(requestParameters.productId, requestParameters.distillIntentBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for intentServiceDistillIntent operation in IntentServiceApi.
 */
export interface IntentServiceApiIntentServiceDistillIntentRequest {
    /**
     * Product whose requirement tree the intent is reconciled against.
     */
    readonly productId: string

    readonly distillIntentBody: DistillIntentBody
}

/**
 * IntentServiceApi - object-oriented interface
 */
export class IntentServiceApi extends BaseAPI {
    /**
     * 
     * @param {IntentServiceApiIntentServiceDistillIntentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intentServiceDistillIntent(requestParameters: IntentServiceApiIntentServiceDistillIntentRequest, options?: RawAxiosRequestConfig) {
        return IntentServiceApiFp(this.configuration).intentServiceDistillIntent(requestParameters.productId, requestParameters.distillIntentBody, options).then((request) => request(this.axios, this.basePath));
    }
}

