/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetIntentSessionResponse } from '../model';
// @ts-ignore
import type { ListIntentSessionsResponse } from '../model';
// @ts-ignore
import type { RecordSessionSettlementBody } from '../model';
// @ts-ignore
import type { RecordSessionSettlementResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { UpsertIntentSessionBody } from '../model';
// @ts-ignore
import type { UpsertIntentSessionResponse } from '../model';
/**
 * IntentSessionServiceApi - axios parameter creator
 */
export const IntentSessionServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Fetches one session by id.
         * @param {string} productId 
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceGetIntentSession: async (productId: string, sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('intentSessionServiceGetIntentSession', 'productId', productId)
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('intentSessionServiceGetIntentSession', 'sessionId', sessionId)
            const localVarPath = `/v1/products/{productId}/intent-sessions/{sessionId}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"sessionId"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Filter by status, git_branch (resolving \"which session, if any, has this branch open\" for cross-machine continuation), or branch_id. Also serves as the capability probe for the whole RPC family: an older server 404s this collection route. effective_status (\"expired\" | \"stale\") filters by the derived-expiry predicate instead of the stored status column — see IntentSession.effective_status — and is rejected together with status.
         * @summary Lists a product\'s sessions, most recently active first.
         * @param {string} productId 
         * @param {string} [status] optional filter — the stored column, verbatim
         * @param {string} [gitBranch] optional filter — cross-machine \&quot;find my open session\&quot;
         * @param {string} [branchId] optional filter
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [effectiveStatus] effective_status is an optional filter selecting by the DERIVED status instead of the stored column: \&quot;expired\&quot; (provisional sessions idle past the provisional TTL) or \&quot;stale\&quot; (materialized sessions idle past the materialized TTL). Mutually exclusive with status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceListIntentSessions: async (productId: string, status?: string, gitBranch?: string, branchId?: string, paginationPageSize?: number, paginationPageToken?: string, effectiveStatus?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('intentSessionServiceListIntentSessions', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/intent-sessions`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (gitBranch !== undefined) {
                localVarQueryParameter['gitBranch'] = gitBranch;
            }

            if (branchId !== undefined) {
                localVarQueryParameter['branchId'] = branchId;
            }

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            if (effectiveStatus !== undefined) {
                localVarQueryParameter['effectiveStatus'] = effectiveStatus;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * items are merged onto the stored settlement by item_id: resending an item_id replaces its entry (the idempotent retry path after a partial failure), a new item_id appends. nothing_to_distill replaces wholesale and is mutually exclusive with items — sending one clears the other on the stored row; sending both in the same request is rejected. Validation here is structural only (enum membership, non-empty reason, id fields parsing as UUIDs) — the CLI enforces the semantic rules (e.g. judged_ids required when hops-0 is non-empty) since the server has no way to know hops-0.
         * @summary Records or amends a session\'s settlement decision.
         * @param {string} productId 
         * @param {string} sessionId 
         * @param {RecordSessionSettlementBody} recordSessionSettlementBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceRecordSessionSettlement: async (productId: string, sessionId: string, recordSessionSettlementBody: RecordSessionSettlementBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('intentSessionServiceRecordSessionSettlement', 'productId', productId)
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('intentSessionServiceRecordSessionSettlement', 'sessionId', sessionId)
            // verify required parameter 'recordSessionSettlementBody' is not null or undefined
            assertParamExists('intentSessionServiceRecordSessionSettlement', 'recordSessionSettlementBody', recordSessionSettlementBody)
            const localVarPath = `/v1/products/{productId}/intent-sessions/{sessionId}:settle`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"sessionId"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recordSessionSettlementBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Only fields set in the request overwrite; every other column on the existing row is left as-is. Creating a session (the first call for that id) requires objective. status is forward-only (provisional -> materialized -> closed); a closed session rejects any further upsert, including one that doesn\'t touch status. Every call refreshes last_activity_at. radius_drops, if present, are recorded as radius_drop judgements under their supersede key (session_id, phase, sorted requirement_ids).
         * @summary Creates or patches a session, keyed by the client-generated session id.
         * @param {string} productId 
         * @param {UpsertIntentSessionBody} upsertIntentSessionBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceUpsertIntentSession: async (productId: string, upsertIntentSessionBody: UpsertIntentSessionBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('intentSessionServiceUpsertIntentSession', 'productId', productId)
            // verify required parameter 'upsertIntentSessionBody' is not null or undefined
            assertParamExists('intentSessionServiceUpsertIntentSession', 'upsertIntentSessionBody', upsertIntentSessionBody)
            const localVarPath = `/v1/products/{productId}/intent-sessions`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertIntentSessionBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IntentSessionServiceApi - functional programming interface
 */
export const IntentSessionServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IntentSessionServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Fetches one session by id.
         * @param {string} productId 
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intentSessionServiceGetIntentSession(productId: string, sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetIntentSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intentSessionServiceGetIntentSession(productId, sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IntentSessionServiceApi.intentSessionServiceGetIntentSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Filter by status, git_branch (resolving \"which session, if any, has this branch open\" for cross-machine continuation), or branch_id. Also serves as the capability probe for the whole RPC family: an older server 404s this collection route. effective_status (\"expired\" | \"stale\") filters by the derived-expiry predicate instead of the stored status column — see IntentSession.effective_status — and is rejected together with status.
         * @summary Lists a product\'s sessions, most recently active first.
         * @param {string} productId 
         * @param {string} [status] optional filter — the stored column, verbatim
         * @param {string} [gitBranch] optional filter — cross-machine \&quot;find my open session\&quot;
         * @param {string} [branchId] optional filter
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [effectiveStatus] effective_status is an optional filter selecting by the DERIVED status instead of the stored column: \&quot;expired\&quot; (provisional sessions idle past the provisional TTL) or \&quot;stale\&quot; (materialized sessions idle past the materialized TTL). Mutually exclusive with status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intentSessionServiceListIntentSessions(productId: string, status?: string, gitBranch?: string, branchId?: string, paginationPageSize?: number, paginationPageToken?: string, effectiveStatus?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListIntentSessionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intentSessionServiceListIntentSessions(productId, status, gitBranch, branchId, paginationPageSize, paginationPageToken, effectiveStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IntentSessionServiceApi.intentSessionServiceListIntentSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * items are merged onto the stored settlement by item_id: resending an item_id replaces its entry (the idempotent retry path after a partial failure), a new item_id appends. nothing_to_distill replaces wholesale and is mutually exclusive with items — sending one clears the other on the stored row; sending both in the same request is rejected. Validation here is structural only (enum membership, non-empty reason, id fields parsing as UUIDs) — the CLI enforces the semantic rules (e.g. judged_ids required when hops-0 is non-empty) since the server has no way to know hops-0.
         * @summary Records or amends a session\'s settlement decision.
         * @param {string} productId 
         * @param {string} sessionId 
         * @param {RecordSessionSettlementBody} recordSessionSettlementBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intentSessionServiceRecordSessionSettlement(productId: string, sessionId: string, recordSessionSettlementBody: RecordSessionSettlementBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecordSessionSettlementResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intentSessionServiceRecordSessionSettlement(productId, sessionId, recordSessionSettlementBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IntentSessionServiceApi.intentSessionServiceRecordSessionSettlement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Only fields set in the request overwrite; every other column on the existing row is left as-is. Creating a session (the first call for that id) requires objective. status is forward-only (provisional -> materialized -> closed); a closed session rejects any further upsert, including one that doesn\'t touch status. Every call refreshes last_activity_at. radius_drops, if present, are recorded as radius_drop judgements under their supersede key (session_id, phase, sorted requirement_ids).
         * @summary Creates or patches a session, keyed by the client-generated session id.
         * @param {string} productId 
         * @param {UpsertIntentSessionBody} upsertIntentSessionBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intentSessionServiceUpsertIntentSession(productId: string, upsertIntentSessionBody: UpsertIntentSessionBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpsertIntentSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intentSessionServiceUpsertIntentSession(productId, upsertIntentSessionBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IntentSessionServiceApi.intentSessionServiceUpsertIntentSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IntentSessionServiceApi - factory interface
 */
export const IntentSessionServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IntentSessionServiceApiFp(configuration)
    return {
        /**
         * 
         * @summary Fetches one session by id.
         * @param {IntentSessionServiceApiIntentSessionServiceGetIntentSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceGetIntentSession(requestParameters: IntentSessionServiceApiIntentSessionServiceGetIntentSessionRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetIntentSessionResponse> {
            return localVarFp.intentSessionServiceGetIntentSession(requestParameters.productId, requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Filter by status, git_branch (resolving \"which session, if any, has this branch open\" for cross-machine continuation), or branch_id. Also serves as the capability probe for the whole RPC family: an older server 404s this collection route. effective_status (\"expired\" | \"stale\") filters by the derived-expiry predicate instead of the stored status column — see IntentSession.effective_status — and is rejected together with status.
         * @summary Lists a product\'s sessions, most recently active first.
         * @param {IntentSessionServiceApiIntentSessionServiceListIntentSessionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceListIntentSessions(requestParameters: IntentSessionServiceApiIntentSessionServiceListIntentSessionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListIntentSessionsResponse> {
            return localVarFp.intentSessionServiceListIntentSessions(requestParameters.productId, requestParameters.status, requestParameters.gitBranch, requestParameters.branchId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.effectiveStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * items are merged onto the stored settlement by item_id: resending an item_id replaces its entry (the idempotent retry path after a partial failure), a new item_id appends. nothing_to_distill replaces wholesale and is mutually exclusive with items — sending one clears the other on the stored row; sending both in the same request is rejected. Validation here is structural only (enum membership, non-empty reason, id fields parsing as UUIDs) — the CLI enforces the semantic rules (e.g. judged_ids required when hops-0 is non-empty) since the server has no way to know hops-0.
         * @summary Records or amends a session\'s settlement decision.
         * @param {IntentSessionServiceApiIntentSessionServiceRecordSessionSettlementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceRecordSessionSettlement(requestParameters: IntentSessionServiceApiIntentSessionServiceRecordSessionSettlementRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecordSessionSettlementResponse> {
            return localVarFp.intentSessionServiceRecordSessionSettlement(requestParameters.productId, requestParameters.sessionId, requestParameters.recordSessionSettlementBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Only fields set in the request overwrite; every other column on the existing row is left as-is. Creating a session (the first call for that id) requires objective. status is forward-only (provisional -> materialized -> closed); a closed session rejects any further upsert, including one that doesn\'t touch status. Every call refreshes last_activity_at. radius_drops, if present, are recorded as radius_drop judgements under their supersede key (session_id, phase, sorted requirement_ids).
         * @summary Creates or patches a session, keyed by the client-generated session id.
         * @param {IntentSessionServiceApiIntentSessionServiceUpsertIntentSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intentSessionServiceUpsertIntentSession(requestParameters: IntentSessionServiceApiIntentSessionServiceUpsertIntentSessionRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpsertIntentSessionResponse> {
            return localVarFp.intentSessionServiceUpsertIntentSession(requestParameters.productId, requestParameters.upsertIntentSessionBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for intentSessionServiceGetIntentSession operation in IntentSessionServiceApi.
 */
export interface IntentSessionServiceApiIntentSessionServiceGetIntentSessionRequest {
    readonly productId: string

    readonly sessionId: string
}

/**
 * Request parameters for intentSessionServiceListIntentSessions operation in IntentSessionServiceApi.
 */
export interface IntentSessionServiceApiIntentSessionServiceListIntentSessionsRequest {
    readonly productId: string

    /**
     * optional filter — the stored column, verbatim
     */
    readonly status?: string

    /**
     * optional filter — cross-machine \&quot;find my open session\&quot;
     */
    readonly gitBranch?: string

    /**
     * optional filter
     */
    readonly branchId?: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string

    /**
     * effective_status is an optional filter selecting by the DERIVED status instead of the stored column: \&quot;expired\&quot; (provisional sessions idle past the provisional TTL) or \&quot;stale\&quot; (materialized sessions idle past the materialized TTL). Mutually exclusive with status.
     */
    readonly effectiveStatus?: string
}

/**
 * Request parameters for intentSessionServiceRecordSessionSettlement operation in IntentSessionServiceApi.
 */
export interface IntentSessionServiceApiIntentSessionServiceRecordSessionSettlementRequest {
    readonly productId: string

    readonly sessionId: string

    readonly recordSessionSettlementBody: RecordSessionSettlementBody
}

/**
 * Request parameters for intentSessionServiceUpsertIntentSession operation in IntentSessionServiceApi.
 */
export interface IntentSessionServiceApiIntentSessionServiceUpsertIntentSessionRequest {
    readonly productId: string

    readonly upsertIntentSessionBody: UpsertIntentSessionBody
}

/**
 * IntentSessionServiceApi - object-oriented interface
 */
export class IntentSessionServiceApi extends BaseAPI {
    /**
     * 
     * @summary Fetches one session by id.
     * @param {IntentSessionServiceApiIntentSessionServiceGetIntentSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intentSessionServiceGetIntentSession(requestParameters: IntentSessionServiceApiIntentSessionServiceGetIntentSessionRequest, options?: RawAxiosRequestConfig) {
        return IntentSessionServiceApiFp(this.configuration).intentSessionServiceGetIntentSession(requestParameters.productId, requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Filter by status, git_branch (resolving \"which session, if any, has this branch open\" for cross-machine continuation), or branch_id. Also serves as the capability probe for the whole RPC family: an older server 404s this collection route. effective_status (\"expired\" | \"stale\") filters by the derived-expiry predicate instead of the stored status column — see IntentSession.effective_status — and is rejected together with status.
     * @summary Lists a product\'s sessions, most recently active first.
     * @param {IntentSessionServiceApiIntentSessionServiceListIntentSessionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intentSessionServiceListIntentSessions(requestParameters: IntentSessionServiceApiIntentSessionServiceListIntentSessionsRequest, options?: RawAxiosRequestConfig) {
        return IntentSessionServiceApiFp(this.configuration).intentSessionServiceListIntentSessions(requestParameters.productId, requestParameters.status, requestParameters.gitBranch, requestParameters.branchId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.effectiveStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * items are merged onto the stored settlement by item_id: resending an item_id replaces its entry (the idempotent retry path after a partial failure), a new item_id appends. nothing_to_distill replaces wholesale and is mutually exclusive with items — sending one clears the other on the stored row; sending both in the same request is rejected. Validation here is structural only (enum membership, non-empty reason, id fields parsing as UUIDs) — the CLI enforces the semantic rules (e.g. judged_ids required when hops-0 is non-empty) since the server has no way to know hops-0.
     * @summary Records or amends a session\'s settlement decision.
     * @param {IntentSessionServiceApiIntentSessionServiceRecordSessionSettlementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intentSessionServiceRecordSessionSettlement(requestParameters: IntentSessionServiceApiIntentSessionServiceRecordSessionSettlementRequest, options?: RawAxiosRequestConfig) {
        return IntentSessionServiceApiFp(this.configuration).intentSessionServiceRecordSessionSettlement(requestParameters.productId, requestParameters.sessionId, requestParameters.recordSessionSettlementBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Only fields set in the request overwrite; every other column on the existing row is left as-is. Creating a session (the first call for that id) requires objective. status is forward-only (provisional -> materialized -> closed); a closed session rejects any further upsert, including one that doesn\'t touch status. Every call refreshes last_activity_at. radius_drops, if present, are recorded as radius_drop judgements under their supersede key (session_id, phase, sorted requirement_ids).
     * @summary Creates or patches a session, keyed by the client-generated session id.
     * @param {IntentSessionServiceApiIntentSessionServiceUpsertIntentSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intentSessionServiceUpsertIntentSession(requestParameters: IntentSessionServiceApiIntentSessionServiceUpsertIntentSessionRequest, options?: RawAxiosRequestConfig) {
        return IntentSessionServiceApiFp(this.configuration).intentSessionServiceUpsertIntentSession(requestParameters.productId, requestParameters.upsertIntentSessionBody, options).then((request) => request(this.axios, this.basePath));
    }
}

