/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConfirmSourceMapUploadResponse } from '../model';
// @ts-ignore
import type { CreateSourceMapUploadBody } from '../model';
// @ts-ignore
import type { CreateSourceMapUploadResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
/**
 * IssueServiceApi - axios parameter creator
 */
export const IssueServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Validates the staged object and atomically promotes it to live, so error events carrying the same debug_id resolve to original sources. Returns metadata only — never a download URL (source maps stay private). Billing-exempt: addressed by source-map id (the product-gated entry point is CreateSourceMapUpload); source maps are observability infra, not a billed cap.
         * @summary Finalizes a source-map upload (phase 2 of 2).
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issueServiceConfirmSourceMapUpload: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('issueServiceConfirmSourceMapUpload', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('issueServiceConfirmSourceMapUpload', 'body', body)
            const localVarPath = `/v1/sourcemaps/{id}:confirm`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a pending source-map row keyed by debug_id and returns a presigned PUT URL to a staging key. Upload the raw map bytes to upload_url, then call ConfirmSourceMapUpload with the returned id to promote it.
         * @summary Starts a source-map upload (phase 1 of 2).
         * @param {string} productId 
         * @param {CreateSourceMapUploadBody} createSourceMapUploadBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issueServiceCreateSourceMapUpload: async (productId: string, createSourceMapUploadBody: CreateSourceMapUploadBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('issueServiceCreateSourceMapUpload', 'productId', productId)
            // verify required parameter 'createSourceMapUploadBody' is not null or undefined
            assertParamExists('issueServiceCreateSourceMapUpload', 'createSourceMapUploadBody', createSourceMapUploadBody)
            const localVarPath = `/v1/products/{productId}/sourcemaps`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSourceMapUploadBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IssueServiceApi - functional programming interface
 */
export const IssueServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IssueServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * Validates the staged object and atomically promotes it to live, so error events carrying the same debug_id resolve to original sources. Returns metadata only — never a download URL (source maps stay private). Billing-exempt: addressed by source-map id (the product-gated entry point is CreateSourceMapUpload); source maps are observability infra, not a billed cap.
         * @summary Finalizes a source-map upload (phase 2 of 2).
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async issueServiceConfirmSourceMapUpload(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConfirmSourceMapUploadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.issueServiceConfirmSourceMapUpload(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IssueServiceApi.issueServiceConfirmSourceMapUpload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a pending source-map row keyed by debug_id and returns a presigned PUT URL to a staging key. Upload the raw map bytes to upload_url, then call ConfirmSourceMapUpload with the returned id to promote it.
         * @summary Starts a source-map upload (phase 1 of 2).
         * @param {string} productId 
         * @param {CreateSourceMapUploadBody} createSourceMapUploadBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async issueServiceCreateSourceMapUpload(productId: string, createSourceMapUploadBody: CreateSourceMapUploadBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateSourceMapUploadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.issueServiceCreateSourceMapUpload(productId, createSourceMapUploadBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IssueServiceApi.issueServiceCreateSourceMapUpload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IssueServiceApi - factory interface
 */
export const IssueServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IssueServiceApiFp(configuration)
    return {
        /**
         * Validates the staged object and atomically promotes it to live, so error events carrying the same debug_id resolve to original sources. Returns metadata only — never a download URL (source maps stay private). Billing-exempt: addressed by source-map id (the product-gated entry point is CreateSourceMapUpload); source maps are observability infra, not a billed cap.
         * @summary Finalizes a source-map upload (phase 2 of 2).
         * @param {IssueServiceApiIssueServiceConfirmSourceMapUploadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issueServiceConfirmSourceMapUpload(requestParameters: IssueServiceApiIssueServiceConfirmSourceMapUploadRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConfirmSourceMapUploadResponse> {
            return localVarFp.issueServiceConfirmSourceMapUpload(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a pending source-map row keyed by debug_id and returns a presigned PUT URL to a staging key. Upload the raw map bytes to upload_url, then call ConfirmSourceMapUpload with the returned id to promote it.
         * @summary Starts a source-map upload (phase 1 of 2).
         * @param {IssueServiceApiIssueServiceCreateSourceMapUploadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issueServiceCreateSourceMapUpload(requestParameters: IssueServiceApiIssueServiceCreateSourceMapUploadRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateSourceMapUploadResponse> {
            return localVarFp.issueServiceCreateSourceMapUpload(requestParameters.productId, requestParameters.createSourceMapUploadBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for issueServiceConfirmSourceMapUpload operation in IssueServiceApi.
 */
export interface IssueServiceApiIssueServiceConfirmSourceMapUploadRequest {
    readonly id: string

    readonly body: object
}

/**
 * Request parameters for issueServiceCreateSourceMapUpload operation in IssueServiceApi.
 */
export interface IssueServiceApiIssueServiceCreateSourceMapUploadRequest {
    readonly productId: string

    readonly createSourceMapUploadBody: CreateSourceMapUploadBody
}

/**
 * IssueServiceApi - object-oriented interface
 */
export class IssueServiceApi extends BaseAPI {
    /**
     * Validates the staged object and atomically promotes it to live, so error events carrying the same debug_id resolve to original sources. Returns metadata only — never a download URL (source maps stay private). Billing-exempt: addressed by source-map id (the product-gated entry point is CreateSourceMapUpload); source maps are observability infra, not a billed cap.
     * @summary Finalizes a source-map upload (phase 2 of 2).
     * @param {IssueServiceApiIssueServiceConfirmSourceMapUploadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public issueServiceConfirmSourceMapUpload(requestParameters: IssueServiceApiIssueServiceConfirmSourceMapUploadRequest, options?: RawAxiosRequestConfig) {
        return IssueServiceApiFp(this.configuration).issueServiceConfirmSourceMapUpload(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a pending source-map row keyed by debug_id and returns a presigned PUT URL to a staging key. Upload the raw map bytes to upload_url, then call ConfirmSourceMapUpload with the returned id to promote it.
     * @summary Starts a source-map upload (phase 1 of 2).
     * @param {IssueServiceApiIssueServiceCreateSourceMapUploadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public issueServiceCreateSourceMapUpload(requestParameters: IssueServiceApiIssueServiceCreateSourceMapUploadRequest, options?: RawAxiosRequestConfig) {
        return IssueServiceApiFp(this.configuration).issueServiceCreateSourceMapUpload(requestParameters.productId, requestParameters.createSourceMapUploadBody, options).then((request) => request(this.axios, this.basePath));
    }
}

