/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateReleaseBody } from '../model';
// @ts-ignore
import type { CreateReleaseResponse } from '../model';
// @ts-ignore
import type { GetReleaseResponse } from '../model';
// @ts-ignore
import type { ListReleasesResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
/**
 * ReleaseServiceApi - axios parameter creator
 */
export const ReleaseServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a release from an external source (CI/SDK). Idempotent upsert on (product, version, environment). The environment is matched by slug and auto-created if unknown.
         * @param {string} productId 
         * @param {CreateReleaseBody} createReleaseBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceCreateRelease: async (productId: string, createReleaseBody: CreateReleaseBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('releaseServiceCreateRelease', 'productId', productId)
            // verify required parameter 'createReleaseBody' is not null or undefined
            assertParamExists('releaseServiceCreateRelease', 'createReleaseBody', createReleaseBody)
            const localVarPath = `/v1/products/{productId}/releases`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReleaseBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceGetRelease: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('releaseServiceGetRelease', 'id', id)
            const localVarPath = `/v1/releases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [environment] optional environment slug filter
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceListReleases: async (productId: string, environment?: string, paginationPageSize?: number, paginationPageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('releaseServiceListReleases', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/releases`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (environment !== undefined) {
                localVarQueryParameter['environment'] = environment;
            }

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReleaseServiceApi - functional programming interface
 */
export const ReleaseServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReleaseServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a release from an external source (CI/SDK). Idempotent upsert on (product, version, environment). The environment is matched by slug and auto-created if unknown.
         * @param {string} productId 
         * @param {CreateReleaseBody} createReleaseBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releaseServiceCreateRelease(productId: string, createReleaseBody: CreateReleaseBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateReleaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releaseServiceCreateRelease(productId, createReleaseBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleaseServiceApi.releaseServiceCreateRelease']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releaseServiceGetRelease(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetReleaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releaseServiceGetRelease(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleaseServiceApi.releaseServiceGetRelease']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [environment] optional environment slug filter
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releaseServiceListReleases(productId: string, environment?: string, paginationPageSize?: number, paginationPageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListReleasesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releaseServiceListReleases(productId, environment, paginationPageSize, paginationPageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleaseServiceApi.releaseServiceListReleases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReleaseServiceApi - factory interface
 */
export const ReleaseServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReleaseServiceApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a release from an external source (CI/SDK). Idempotent upsert on (product, version, environment). The environment is matched by slug and auto-created if unknown.
         * @param {ReleaseServiceApiReleaseServiceCreateReleaseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceCreateRelease(requestParameters: ReleaseServiceApiReleaseServiceCreateReleaseRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateReleaseResponse> {
            return localVarFp.releaseServiceCreateRelease(requestParameters.productId, requestParameters.createReleaseBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ReleaseServiceApiReleaseServiceGetReleaseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceGetRelease(requestParameters: ReleaseServiceApiReleaseServiceGetReleaseRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetReleaseResponse> {
            return localVarFp.releaseServiceGetRelease(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ReleaseServiceApiReleaseServiceListReleasesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releaseServiceListReleases(requestParameters: ReleaseServiceApiReleaseServiceListReleasesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListReleasesResponse> {
            return localVarFp.releaseServiceListReleases(requestParameters.productId, requestParameters.environment, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for releaseServiceCreateRelease operation in ReleaseServiceApi.
 */
export interface ReleaseServiceApiReleaseServiceCreateReleaseRequest {
    readonly productId: string

    readonly createReleaseBody: CreateReleaseBody
}

/**
 * Request parameters for releaseServiceGetRelease operation in ReleaseServiceApi.
 */
export interface ReleaseServiceApiReleaseServiceGetReleaseRequest {
    readonly id: string
}

/**
 * Request parameters for releaseServiceListReleases operation in ReleaseServiceApi.
 */
export interface ReleaseServiceApiReleaseServiceListReleasesRequest {
    readonly productId: string

    /**
     * optional environment slug filter
     */
    readonly environment?: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string
}

/**
 * ReleaseServiceApi - object-oriented interface
 */
export class ReleaseServiceApi extends BaseAPI {
    /**
     * 
     * @summary Create a release from an external source (CI/SDK). Idempotent upsert on (product, version, environment). The environment is matched by slug and auto-created if unknown.
     * @param {ReleaseServiceApiReleaseServiceCreateReleaseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public releaseServiceCreateRelease(requestParameters: ReleaseServiceApiReleaseServiceCreateReleaseRequest, options?: RawAxiosRequestConfig) {
        return ReleaseServiceApiFp(this.configuration).releaseServiceCreateRelease(requestParameters.productId, requestParameters.createReleaseBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ReleaseServiceApiReleaseServiceGetReleaseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public releaseServiceGetRelease(requestParameters: ReleaseServiceApiReleaseServiceGetReleaseRequest, options?: RawAxiosRequestConfig) {
        return ReleaseServiceApiFp(this.configuration).releaseServiceGetRelease(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ReleaseServiceApiReleaseServiceListReleasesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public releaseServiceListReleases(requestParameters: ReleaseServiceApiReleaseServiceListReleasesRequest, options?: RawAxiosRequestConfig) {
        return ReleaseServiceApiFp(this.configuration).releaseServiceListReleases(requestParameters.productId, requestParameters.environment, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(this.axios, this.basePath));
    }
}

