/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateTestBody } from '../model';
// @ts-ignore
import type { CreateTestResponse } from '../model';
// @ts-ignore
import type { DeriveTestLinksResponse } from '../model';
// @ts-ignore
import type { GetTestResponse } from '../model';
// @ts-ignore
import type { IngestTestsBody } from '../model';
// @ts-ignore
import type { IngestTestsResponse } from '../model';
// @ts-ignore
import type { LinkRequirementBody } from '../model';
// @ts-ignore
import type { ListBranchLinkProposalsResponse } from '../model';
// @ts-ignore
import type { ListLinksResponse } from '../model';
// @ts-ignore
import type { ListTestsResponse } from '../model';
// @ts-ignore
import type { ReviewBranchLinkProposalsBody } from '../model';
// @ts-ignore
import type { ReviewBranchLinkProposalsResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
// @ts-ignore
import type { UpdateTestBody } from '../model';
// @ts-ignore
import type { UpdateTestResponse } from '../model';
/**
 * TestServiceApi - axios parameter creator
 */
export const TestServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productId 
         * @param {CreateTestBody} createTestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceCreateTest: async (productId: string, createTestBody: CreateTestBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testServiceCreateTest', 'productId', productId)
            // verify required parameter 'createTestBody' is not null or undefined
            assertParamExists('testServiceCreateTest', 'createTestBody', createTestBody)
            const localVarPath = `/v1/products/{productId}/tests`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceDeleteTest: async (id: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('testServiceDeleteTest', 'id', id)
            const localVarPath = `/v1/tests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary DeriveTestLinks matches requirement repo_file anchors against tests\' file_path: exact-file matches are auto-linked (durable, moves the gate), directory-proximity matches are returned for an agent to confirm via LinkRequirement. Idempotent.
         * @param {string} productId 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceDeriveTestLinks: async (productId: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testServiceDeriveTestLinks', 'productId', productId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('testServiceDeriveTestLinks', 'body', body)
            const localVarPath = `/v1/products/{productId}/test-links:derive`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceGetTest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('testServiceGetTest', 'id', id)
            const localVarPath = `/v1/tests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary IngestTests is the reporter-friendly batch upsert endpoint. Idempotent on (product, branch, external_id). Server-validates the entire batch upfront, then either applies all changes or returns 422 with the per-entry errors. Max 1000 tests per call (enforced server-side).
         * @param {string} productId 
         * @param {IngestTestsBody} ingestTestsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceIngestTests: async (productId: string, ingestTestsBody: IngestTestsBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testServiceIngestTests', 'productId', productId)
            // verify required parameter 'ingestTestsBody' is not null or undefined
            assertParamExists('testServiceIngestTests', 'ingestTestsBody', ingestTestsBody)
            const localVarPath = `/v1/products/{productId}/tests:ingest`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ingestTestsBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} testId 
         * @param {LinkRequirementBody} linkRequirementBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceLinkRequirement: async (testId: string, linkRequirementBody: LinkRequirementBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'testId' is not null or undefined
            assertParamExists('testServiceLinkRequirement', 'testId', testId)
            // verify required parameter 'linkRequirementBody' is not null or undefined
            assertParamExists('testServiceLinkRequirement', 'linkRequirementBody', linkRequirementBody)
            const localVarPath = `/v1/tests/{testId}/links`
                .replace(`{${"testId"}}`, encodeURIComponent(String(testId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(linkRequirementBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} branchId 
         * @param {Array<string>} [statuses] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListBranchLinkProposals: async (branchId: string, statuses?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'branchId' is not null or undefined
            assertParamExists('testServiceListBranchLinkProposals', 'branchId', branchId)
            const localVarPath = `/v1/branches/{branchId}/link-proposals`
                .replace(`{${"branchId"}}`, encodeURIComponent(String(branchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (statuses) {
                localVarQueryParameter['statuses'] = statuses;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} testId 
         * @param {string} [branch] when set, links are read-only via COW
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListLinks: async (testId: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'testId' is not null or undefined
            assertParamExists('testServiceListLinks', 'testId', testId)
            const localVarPath = `/v1/tests/{testId}/links`
                .replace(`{${"testId"}}`, encodeURIComponent(String(testId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListTests: async (productId: string, paginationPageSize?: number, paginationPageToken?: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testServiceListTests', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/tests`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} branchId 
         * @param {ReviewBranchLinkProposalsBody} reviewBranchLinkProposalsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceReviewBranchLinkProposals: async (branchId: string, reviewBranchLinkProposalsBody: ReviewBranchLinkProposalsBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'branchId' is not null or undefined
            assertParamExists('testServiceReviewBranchLinkProposals', 'branchId', branchId)
            // verify required parameter 'reviewBranchLinkProposalsBody' is not null or undefined
            assertParamExists('testServiceReviewBranchLinkProposals', 'reviewBranchLinkProposalsBody', reviewBranchLinkProposalsBody)
            const localVarPath = `/v1/branches/{branchId}/link-proposals:review`
                .replace(`{${"branchId"}}`, encodeURIComponent(String(branchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reviewBranchLinkProposalsBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} testId 
         * @param {string} requirementId 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceUnlinkRequirement: async (testId: string, requirementId: string, branch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'testId' is not null or undefined
            assertParamExists('testServiceUnlinkRequirement', 'testId', testId)
            // verify required parameter 'requirementId' is not null or undefined
            assertParamExists('testServiceUnlinkRequirement', 'requirementId', requirementId)
            const localVarPath = `/v1/tests/{testId}/links/{requirementId}`
                .replace(`{${"testId"}}`, encodeURIComponent(String(testId)))
                .replace(`{${"requirementId"}}`, encodeURIComponent(String(requirementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateTestBody} updateTestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceUpdateTest: async (id: string, updateTestBody: UpdateTestBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('testServiceUpdateTest', 'id', id)
            // verify required parameter 'updateTestBody' is not null or undefined
            assertParamExists('testServiceUpdateTest', 'updateTestBody', updateTestBody)
            const localVarPath = `/v1/tests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestServiceApi - functional programming interface
 */
export const TestServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productId 
         * @param {CreateTestBody} createTestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceCreateTest(productId: string, createTestBody: CreateTestBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceCreateTest(productId, createTestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceCreateTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceDeleteTest(id: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceDeleteTest(id, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceDeleteTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary DeriveTestLinks matches requirement repo_file anchors against tests\' file_path: exact-file matches are auto-linked (durable, moves the gate), directory-proximity matches are returned for an agent to confirm via LinkRequirement. Idempotent.
         * @param {string} productId 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceDeriveTestLinks(productId: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeriveTestLinksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceDeriveTestLinks(productId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceDeriveTestLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceGetTest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceGetTest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceGetTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary IngestTests is the reporter-friendly batch upsert endpoint. Idempotent on (product, branch, external_id). Server-validates the entire batch upfront, then either applies all changes or returns 422 with the per-entry errors. Max 1000 tests per call (enforced server-side).
         * @param {string} productId 
         * @param {IngestTestsBody} ingestTestsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceIngestTests(productId: string, ingestTestsBody: IngestTestsBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngestTestsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceIngestTests(productId, ingestTestsBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceIngestTests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} testId 
         * @param {LinkRequirementBody} linkRequirementBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceLinkRequirement(testId: string, linkRequirementBody: LinkRequirementBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceLinkRequirement(testId, linkRequirementBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceLinkRequirement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} branchId 
         * @param {Array<string>} [statuses] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceListBranchLinkProposals(branchId: string, statuses?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBranchLinkProposalsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceListBranchLinkProposals(branchId, statuses, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceListBranchLinkProposals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} testId 
         * @param {string} [branch] when set, links are read-only via COW
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceListLinks(testId: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListLinksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceListLinks(testId, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceListLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceListTests(productId: string, paginationPageSize?: number, paginationPageToken?: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTestsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceListTests(productId, paginationPageSize, paginationPageToken, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceListTests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} branchId 
         * @param {ReviewBranchLinkProposalsBody} reviewBranchLinkProposalsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceReviewBranchLinkProposals(branchId: string, reviewBranchLinkProposalsBody: ReviewBranchLinkProposalsBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReviewBranchLinkProposalsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceReviewBranchLinkProposals(branchId, reviewBranchLinkProposalsBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceReviewBranchLinkProposals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} testId 
         * @param {string} requirementId 
         * @param {string} [branch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceUnlinkRequirement(testId: string, requirementId: string, branch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceUnlinkRequirement(testId, requirementId, branch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceUnlinkRequirement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateTestBody} updateTestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testServiceUpdateTest(id: string, updateTestBody: UpdateTestBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testServiceUpdateTest(id, updateTestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestServiceApi.testServiceUpdateTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestServiceApi - factory interface
 */
export const TestServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {TestServiceApiTestServiceCreateTestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceCreateTest(requestParameters: TestServiceApiTestServiceCreateTestRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateTestResponse> {
            return localVarFp.testServiceCreateTest(requestParameters.productId, requestParameters.createTestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceDeleteTestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceDeleteTest(requestParameters: TestServiceApiTestServiceDeleteTestRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.testServiceDeleteTest(requestParameters.id, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary DeriveTestLinks matches requirement repo_file anchors against tests\' file_path: exact-file matches are auto-linked (durable, moves the gate), directory-proximity matches are returned for an agent to confirm via LinkRequirement. Idempotent.
         * @param {TestServiceApiTestServiceDeriveTestLinksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceDeriveTestLinks(requestParameters: TestServiceApiTestServiceDeriveTestLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeriveTestLinksResponse> {
            return localVarFp.testServiceDeriveTestLinks(requestParameters.productId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceGetTestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceGetTest(requestParameters: TestServiceApiTestServiceGetTestRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetTestResponse> {
            return localVarFp.testServiceGetTest(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary IngestTests is the reporter-friendly batch upsert endpoint. Idempotent on (product, branch, external_id). Server-validates the entire batch upfront, then either applies all changes or returns 422 with the per-entry errors. Max 1000 tests per call (enforced server-side).
         * @param {TestServiceApiTestServiceIngestTestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceIngestTests(requestParameters: TestServiceApiTestServiceIngestTestsRequest, options?: RawAxiosRequestConfig): AxiosPromise<IngestTestsResponse> {
            return localVarFp.testServiceIngestTests(requestParameters.productId, requestParameters.ingestTestsBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceLinkRequirementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceLinkRequirement(requestParameters: TestServiceApiTestServiceLinkRequirementRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.testServiceLinkRequirement(requestParameters.testId, requestParameters.linkRequirementBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceListBranchLinkProposalsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListBranchLinkProposals(requestParameters: TestServiceApiTestServiceListBranchLinkProposalsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListBranchLinkProposalsResponse> {
            return localVarFp.testServiceListBranchLinkProposals(requestParameters.branchId, requestParameters.statuses, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceListLinksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListLinks(requestParameters: TestServiceApiTestServiceListLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListLinksResponse> {
            return localVarFp.testServiceListLinks(requestParameters.testId, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceListTestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceListTests(requestParameters: TestServiceApiTestServiceListTestsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListTestsResponse> {
            return localVarFp.testServiceListTests(requestParameters.productId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceReviewBranchLinkProposalsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceReviewBranchLinkProposals(requestParameters: TestServiceApiTestServiceReviewBranchLinkProposalsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReviewBranchLinkProposalsResponse> {
            return localVarFp.testServiceReviewBranchLinkProposals(requestParameters.branchId, requestParameters.reviewBranchLinkProposalsBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceUnlinkRequirementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceUnlinkRequirement(requestParameters: TestServiceApiTestServiceUnlinkRequirementRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.testServiceUnlinkRequirement(requestParameters.testId, requestParameters.requirementId, requestParameters.branch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestServiceApiTestServiceUpdateTestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testServiceUpdateTest(requestParameters: TestServiceApiTestServiceUpdateTestRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateTestResponse> {
            return localVarFp.testServiceUpdateTest(requestParameters.id, requestParameters.updateTestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for testServiceCreateTest operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceCreateTestRequest {
    readonly productId: string

    readonly createTestBody: CreateTestBody
}

/**
 * Request parameters for testServiceDeleteTest operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceDeleteTestRequest {
    readonly id: string

    readonly branch?: string
}

/**
 * Request parameters for testServiceDeriveTestLinks operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceDeriveTestLinksRequest {
    readonly productId: string

    readonly body: object
}

/**
 * Request parameters for testServiceGetTest operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceGetTestRequest {
    readonly id: string
}

/**
 * Request parameters for testServiceIngestTests operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceIngestTestsRequest {
    readonly productId: string

    readonly ingestTestsBody: IngestTestsBody
}

/**
 * Request parameters for testServiceLinkRequirement operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceLinkRequirementRequest {
    readonly testId: string

    readonly linkRequirementBody: LinkRequirementBody
}

/**
 * Request parameters for testServiceListBranchLinkProposals operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceListBranchLinkProposalsRequest {
    readonly branchId: string

    readonly statuses?: Array<string>
}

/**
 * Request parameters for testServiceListLinks operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceListLinksRequest {
    readonly testId: string

    /**
     * when set, links are read-only via COW
     */
    readonly branch?: string
}

/**
 * Request parameters for testServiceListTests operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceListTestsRequest {
    readonly productId: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string

    readonly branch?: string
}

/**
 * Request parameters for testServiceReviewBranchLinkProposals operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceReviewBranchLinkProposalsRequest {
    readonly branchId: string

    readonly reviewBranchLinkProposalsBody: ReviewBranchLinkProposalsBody
}

/**
 * Request parameters for testServiceUnlinkRequirement operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceUnlinkRequirementRequest {
    readonly testId: string

    readonly requirementId: string

    readonly branch?: string
}

/**
 * Request parameters for testServiceUpdateTest operation in TestServiceApi.
 */
export interface TestServiceApiTestServiceUpdateTestRequest {
    readonly id: string

    readonly updateTestBody: UpdateTestBody
}

/**
 * TestServiceApi - object-oriented interface
 */
export class TestServiceApi extends BaseAPI {
    /**
     * 
     * @param {TestServiceApiTestServiceCreateTestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceCreateTest(requestParameters: TestServiceApiTestServiceCreateTestRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceCreateTest(requestParameters.productId, requestParameters.createTestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceDeleteTestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceDeleteTest(requestParameters: TestServiceApiTestServiceDeleteTestRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceDeleteTest(requestParameters.id, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary DeriveTestLinks matches requirement repo_file anchors against tests\' file_path: exact-file matches are auto-linked (durable, moves the gate), directory-proximity matches are returned for an agent to confirm via LinkRequirement. Idempotent.
     * @param {TestServiceApiTestServiceDeriveTestLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceDeriveTestLinks(requestParameters: TestServiceApiTestServiceDeriveTestLinksRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceDeriveTestLinks(requestParameters.productId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceGetTestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceGetTest(requestParameters: TestServiceApiTestServiceGetTestRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceGetTest(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary IngestTests is the reporter-friendly batch upsert endpoint. Idempotent on (product, branch, external_id). Server-validates the entire batch upfront, then either applies all changes or returns 422 with the per-entry errors. Max 1000 tests per call (enforced server-side).
     * @param {TestServiceApiTestServiceIngestTestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceIngestTests(requestParameters: TestServiceApiTestServiceIngestTestsRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceIngestTests(requestParameters.productId, requestParameters.ingestTestsBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceLinkRequirementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceLinkRequirement(requestParameters: TestServiceApiTestServiceLinkRequirementRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceLinkRequirement(requestParameters.testId, requestParameters.linkRequirementBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceListBranchLinkProposalsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceListBranchLinkProposals(requestParameters: TestServiceApiTestServiceListBranchLinkProposalsRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceListBranchLinkProposals(requestParameters.branchId, requestParameters.statuses, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceListLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceListLinks(requestParameters: TestServiceApiTestServiceListLinksRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceListLinks(requestParameters.testId, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceListTestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceListTests(requestParameters: TestServiceApiTestServiceListTestsRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceListTests(requestParameters.productId, requestParameters.paginationPageSize, requestParameters.paginationPageToken, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceReviewBranchLinkProposalsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceReviewBranchLinkProposals(requestParameters: TestServiceApiTestServiceReviewBranchLinkProposalsRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceReviewBranchLinkProposals(requestParameters.branchId, requestParameters.reviewBranchLinkProposalsBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceUnlinkRequirementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceUnlinkRequirement(requestParameters: TestServiceApiTestServiceUnlinkRequirementRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceUnlinkRequirement(requestParameters.testId, requestParameters.requirementId, requestParameters.branch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestServiceApiTestServiceUpdateTestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testServiceUpdateTest(requestParameters: TestServiceApiTestServiceUpdateTestRequest, options?: RawAxiosRequestConfig) {
        return TestServiceApiFp(this.configuration).testServiceUpdateTest(requestParameters.id, requestParameters.updateTestBody, options).then((request) => request(this.axios, this.basePath));
    }
}

