/* tslint:disable */
/* eslint-disable */
/**
 * Tiden Public API
 * REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AbortTestRunResponse } from '../model';
// @ts-ignore
import type { CompleteTestRunResponse } from '../model';
// @ts-ignore
import type { CreateTestRunBody } from '../model';
// @ts-ignore
import type { CreateTestRunResponse } from '../model';
// @ts-ignore
import type { GetRunAttachmentResponse } from '../model';
// @ts-ignore
import type { GetRunResultResponse } from '../model';
// @ts-ignore
import type { GetRunSummaryResponse } from '../model';
// @ts-ignore
import type { GetTestRunResponse } from '../model';
// @ts-ignore
import type { ListRunResultsResponse } from '../model';
// @ts-ignore
import type { ListTestRunsResponse } from '../model';
// @ts-ignore
import type { ReportResultsBody } from '../model';
// @ts-ignore
import type { ReportResultsResponse } from '../model';
// @ts-ignore
import type { Status } from '../model';
/**
 * TestRunServiceApi - axios parameter creator
 */
export const TestRunServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceAbortTestRun: async (productId: string, runSeq: number, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceAbortTestRun', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceAbortTestRun', 'runSeq', runSeq)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('testRunServiceAbortTestRun', 'body', body)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}:abort`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceCompleteTestRun: async (productId: string, runSeq: number, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceCompleteTestRun', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceCompleteTestRun', 'runSeq', runSeq)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('testRunServiceCompleteTestRun', 'body', body)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}:complete`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {CreateTestRunBody} createTestRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceCreateTestRun: async (productId: string, createTestRunBody: CreateTestRunBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceCreateTestRun', 'productId', productId)
            // verify required parameter 'createTestRunBody' is not null or undefined
            assertParamExists('testRunServiceCreateTestRun', 'createTestRunBody', createTestRunBody)
            const localVarPath = `/v1/products/{productId}/runs`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTestRunBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceDeleteTestRun: async (productId: string, runSeq: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceDeleteTestRun', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceDeleteTestRun', 'runSeq', runSeq)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resolves a content-hash (uploaded via the reporter multipart route POST /v1/products/{product_id}/attachments:upload) to a presigned download URL. Public so reporter/CLI clients and the SPA (JWT) can both fetch; ATTACHMENT_NOT_FOUND (→ 404) for an unknown hash — the drawer renders \"attachment unavailable\" on that.
         * @param {string} productId 
         * @param {string} hash sha256 hex content hash
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunAttachment: async (productId: string, hash: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceGetRunAttachment', 'productId', productId)
            // verify required parameter 'hash' is not null or undefined
            assertParamExists('testRunServiceGetRunAttachment', 'hash', hash)
            const localVarPath = `/v1/products/{productId}/attachments/{hash}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"hash"}}`, encodeURIComponent(String(hash)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {string} resultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunResult: async (productId: string, runSeq: number, resultId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceGetRunResult', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceGetRunResult', 'runSeq', runSeq)
            // verify required parameter 'resultId' is not null or undefined
            assertParamExists('testRunServiceGetRunResult', 'resultId', resultId)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}/results/{resultId}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)))
                .replace(`{${"resultId"}}`, encodeURIComponent(String(resultId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunSummary: async (productId: string, runSeq: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceGetRunSummary', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceGetRunSummary', 'runSeq', runSeq)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}/summary`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetTestRun: async (productId: string, runSeq: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceGetTestRun', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceGetTestRun', 'runSeq', runSeq)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {string} [status] optional filter (latest attempt status)
         * @param {string} [search] optional title substring
         * @param {string} [identityKey] optional: all attempts of one case identity
         * @param {boolean} [latestOnly] collapse retries (default false &#x3D; all rows)
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceListRunResults: async (productId: string, runSeq: number, status?: string, search?: string, identityKey?: string, latestOnly?: boolean, paginationPageSize?: number, paginationPageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceListRunResults', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceListRunResults', 'runSeq', runSeq)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}/results`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (identityKey !== undefined) {
                localVarQueryParameter['identityKey'] = identityKey;
            }

            if (latestOnly !== undefined) {
                localVarQueryParameter['latestOnly'] = latestOnly;
            }

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [status] optional filter
         * @param {string} [environment] optional environment slug filter
         * @param {string} [branch] optional branch_name filter
         * @param {string} [search] optional title substring
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceListTestRuns: async (productId: string, status?: string, environment?: string, branch?: string, search?: string, paginationPageSize?: number, paginationPageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceListTestRuns', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/runs`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (environment !== undefined) {
                localVarQueryParameter['environment'] = environment;
            }

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (paginationPageSize !== undefined) {
                localVarQueryParameter['pagination.pageSize'] = paginationPageSize;
            }

            if (paginationPageToken !== undefined) {
                localVarQueryParameter['pagination.pageToken'] = paginationPageToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {ReportResultsBody} reportResultsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceReportResults: async (productId: string, runSeq: number, reportResultsBody: ReportResultsBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('testRunServiceReportResults', 'productId', productId)
            // verify required parameter 'runSeq' is not null or undefined
            assertParamExists('testRunServiceReportResults', 'runSeq', runSeq)
            // verify required parameter 'reportResultsBody' is not null or undefined
            assertParamExists('testRunServiceReportResults', 'reportResultsBody', reportResultsBody)
            const localVarPath = `/v1/products/{productId}/runs/{runSeq}/results:report`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)))
                .replace(`{${"runSeq"}}`, encodeURIComponent(String(runSeq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reportResultsBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestRunServiceApi - functional programming interface
 */
export const TestRunServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestRunServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceAbortTestRun(productId: string, runSeq: number, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbortTestRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceAbortTestRun(productId, runSeq, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceAbortTestRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceCompleteTestRun(productId: string, runSeq: number, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompleteTestRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceCompleteTestRun(productId, runSeq, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceCompleteTestRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {CreateTestRunBody} createTestRunBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceCreateTestRun(productId: string, createTestRunBody: CreateTestRunBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateTestRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceCreateTestRun(productId, createTestRunBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceCreateTestRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceDeleteTestRun(productId: string, runSeq: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceDeleteTestRun(productId, runSeq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceDeleteTestRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resolves a content-hash (uploaded via the reporter multipart route POST /v1/products/{product_id}/attachments:upload) to a presigned download URL. Public so reporter/CLI clients and the SPA (JWT) can both fetch; ATTACHMENT_NOT_FOUND (→ 404) for an unknown hash — the drawer renders \"attachment unavailable\" on that.
         * @param {string} productId 
         * @param {string} hash sha256 hex content hash
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceGetRunAttachment(productId: string, hash: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRunAttachmentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceGetRunAttachment(productId, hash, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceGetRunAttachment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {string} resultId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceGetRunResult(productId: string, runSeq: number, resultId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRunResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceGetRunResult(productId, runSeq, resultId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceGetRunResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceGetRunSummary(productId: string, runSeq: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRunSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceGetRunSummary(productId, runSeq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceGetRunSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceGetTestRun(productId: string, runSeq: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTestRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceGetTestRun(productId, runSeq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceGetTestRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {string} [status] optional filter (latest attempt status)
         * @param {string} [search] optional title substring
         * @param {string} [identityKey] optional: all attempts of one case identity
         * @param {boolean} [latestOnly] collapse retries (default false &#x3D; all rows)
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceListRunResults(productId: string, runSeq: number, status?: string, search?: string, identityKey?: string, latestOnly?: boolean, paginationPageSize?: number, paginationPageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListRunResultsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceListRunResults(productId, runSeq, status, search, identityKey, latestOnly, paginationPageSize, paginationPageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceListRunResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {string} [status] optional filter
         * @param {string} [environment] optional environment slug filter
         * @param {string} [branch] optional branch_name filter
         * @param {string} [search] optional title substring
         * @param {number} [paginationPageSize] 
         * @param {string} [paginationPageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceListTestRuns(productId: string, status?: string, environment?: string, branch?: string, search?: string, paginationPageSize?: number, paginationPageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTestRunsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceListTestRuns(productId, status, environment, branch, search, paginationPageSize, paginationPageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceListTestRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} productId 
         * @param {number} runSeq 
         * @param {ReportResultsBody} reportResultsBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testRunServiceReportResults(productId: string, runSeq: number, reportResultsBody: ReportResultsBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportResultsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testRunServiceReportResults(productId, runSeq, reportResultsBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestRunServiceApi.testRunServiceReportResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestRunServiceApi - factory interface
 */
export const TestRunServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestRunServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceAbortTestRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceAbortTestRun(requestParameters: TestRunServiceApiTestRunServiceAbortTestRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<AbortTestRunResponse> {
            return localVarFp.testRunServiceAbortTestRun(requestParameters.productId, requestParameters.runSeq, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceCompleteTestRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceCompleteTestRun(requestParameters: TestRunServiceApiTestRunServiceCompleteTestRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<CompleteTestRunResponse> {
            return localVarFp.testRunServiceCompleteTestRun(requestParameters.productId, requestParameters.runSeq, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceCreateTestRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceCreateTestRun(requestParameters: TestRunServiceApiTestRunServiceCreateTestRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateTestRunResponse> {
            return localVarFp.testRunServiceCreateTestRun(requestParameters.productId, requestParameters.createTestRunBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceDeleteTestRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceDeleteTestRun(requestParameters: TestRunServiceApiTestRunServiceDeleteTestRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.testRunServiceDeleteTestRun(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resolves a content-hash (uploaded via the reporter multipart route POST /v1/products/{product_id}/attachments:upload) to a presigned download URL. Public so reporter/CLI clients and the SPA (JWT) can both fetch; ATTACHMENT_NOT_FOUND (→ 404) for an unknown hash — the drawer renders \"attachment unavailable\" on that.
         * @param {TestRunServiceApiTestRunServiceGetRunAttachmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunAttachment(requestParameters: TestRunServiceApiTestRunServiceGetRunAttachmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetRunAttachmentResponse> {
            return localVarFp.testRunServiceGetRunAttachment(requestParameters.productId, requestParameters.hash, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceGetRunResultRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunResult(requestParameters: TestRunServiceApiTestRunServiceGetRunResultRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetRunResultResponse> {
            return localVarFp.testRunServiceGetRunResult(requestParameters.productId, requestParameters.runSeq, requestParameters.resultId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceGetRunSummaryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetRunSummary(requestParameters: TestRunServiceApiTestRunServiceGetRunSummaryRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetRunSummaryResponse> {
            return localVarFp.testRunServiceGetRunSummary(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceGetTestRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceGetTestRun(requestParameters: TestRunServiceApiTestRunServiceGetTestRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetTestRunResponse> {
            return localVarFp.testRunServiceGetTestRun(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceListRunResultsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceListRunResults(requestParameters: TestRunServiceApiTestRunServiceListRunResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListRunResultsResponse> {
            return localVarFp.testRunServiceListRunResults(requestParameters.productId, requestParameters.runSeq, requestParameters.status, requestParameters.search, requestParameters.identityKey, requestParameters.latestOnly, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceListTestRunsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceListTestRuns(requestParameters: TestRunServiceApiTestRunServiceListTestRunsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListTestRunsResponse> {
            return localVarFp.testRunServiceListTestRuns(requestParameters.productId, requestParameters.status, requestParameters.environment, requestParameters.branch, requestParameters.search, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TestRunServiceApiTestRunServiceReportResultsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testRunServiceReportResults(requestParameters: TestRunServiceApiTestRunServiceReportResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportResultsResponse> {
            return localVarFp.testRunServiceReportResults(requestParameters.productId, requestParameters.runSeq, requestParameters.reportResultsBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for testRunServiceAbortTestRun operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceAbortTestRunRequest {
    readonly productId: string

    readonly runSeq: number

    readonly body: object
}

/**
 * Request parameters for testRunServiceCompleteTestRun operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceCompleteTestRunRequest {
    readonly productId: string

    readonly runSeq: number

    readonly body: object
}

/**
 * Request parameters for testRunServiceCreateTestRun operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceCreateTestRunRequest {
    readonly productId: string

    readonly createTestRunBody: CreateTestRunBody
}

/**
 * Request parameters for testRunServiceDeleteTestRun operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceDeleteTestRunRequest {
    readonly productId: string

    readonly runSeq: number
}

/**
 * Request parameters for testRunServiceGetRunAttachment operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceGetRunAttachmentRequest {
    readonly productId: string

    /**
     * sha256 hex content hash
     */
    readonly hash: string
}

/**
 * Request parameters for testRunServiceGetRunResult operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceGetRunResultRequest {
    readonly productId: string

    readonly runSeq: number

    readonly resultId: string
}

/**
 * Request parameters for testRunServiceGetRunSummary operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceGetRunSummaryRequest {
    readonly productId: string

    readonly runSeq: number
}

/**
 * Request parameters for testRunServiceGetTestRun operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceGetTestRunRequest {
    readonly productId: string

    readonly runSeq: number
}

/**
 * Request parameters for testRunServiceListRunResults operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceListRunResultsRequest {
    readonly productId: string

    readonly runSeq: number

    /**
     * optional filter (latest attempt status)
     */
    readonly status?: string

    /**
     * optional title substring
     */
    readonly search?: string

    /**
     * optional: all attempts of one case identity
     */
    readonly identityKey?: string

    /**
     * collapse retries (default false &#x3D; all rows)
     */
    readonly latestOnly?: boolean

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string
}

/**
 * Request parameters for testRunServiceListTestRuns operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceListTestRunsRequest {
    readonly productId: string

    /**
     * optional filter
     */
    readonly status?: string

    /**
     * optional environment slug filter
     */
    readonly environment?: string

    /**
     * optional branch_name filter
     */
    readonly branch?: string

    /**
     * optional title substring
     */
    readonly search?: string

    readonly paginationPageSize?: number

    readonly paginationPageToken?: string
}

/**
 * Request parameters for testRunServiceReportResults operation in TestRunServiceApi.
 */
export interface TestRunServiceApiTestRunServiceReportResultsRequest {
    readonly productId: string

    readonly runSeq: number

    readonly reportResultsBody: ReportResultsBody
}

/**
 * TestRunServiceApi - object-oriented interface
 */
export class TestRunServiceApi extends BaseAPI {
    /**
     * 
     * @param {TestRunServiceApiTestRunServiceAbortTestRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceAbortTestRun(requestParameters: TestRunServiceApiTestRunServiceAbortTestRunRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceAbortTestRun(requestParameters.productId, requestParameters.runSeq, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceCompleteTestRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceCompleteTestRun(requestParameters: TestRunServiceApiTestRunServiceCompleteTestRunRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceCompleteTestRun(requestParameters.productId, requestParameters.runSeq, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceCreateTestRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceCreateTestRun(requestParameters: TestRunServiceApiTestRunServiceCreateTestRunRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceCreateTestRun(requestParameters.productId, requestParameters.createTestRunBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceDeleteTestRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceDeleteTestRun(requestParameters: TestRunServiceApiTestRunServiceDeleteTestRunRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceDeleteTestRun(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resolves a content-hash (uploaded via the reporter multipart route POST /v1/products/{product_id}/attachments:upload) to a presigned download URL. Public so reporter/CLI clients and the SPA (JWT) can both fetch; ATTACHMENT_NOT_FOUND (→ 404) for an unknown hash — the drawer renders \"attachment unavailable\" on that.
     * @param {TestRunServiceApiTestRunServiceGetRunAttachmentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceGetRunAttachment(requestParameters: TestRunServiceApiTestRunServiceGetRunAttachmentRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceGetRunAttachment(requestParameters.productId, requestParameters.hash, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceGetRunResultRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceGetRunResult(requestParameters: TestRunServiceApiTestRunServiceGetRunResultRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceGetRunResult(requestParameters.productId, requestParameters.runSeq, requestParameters.resultId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceGetRunSummaryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceGetRunSummary(requestParameters: TestRunServiceApiTestRunServiceGetRunSummaryRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceGetRunSummary(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceGetTestRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceGetTestRun(requestParameters: TestRunServiceApiTestRunServiceGetTestRunRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceGetTestRun(requestParameters.productId, requestParameters.runSeq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceListRunResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceListRunResults(requestParameters: TestRunServiceApiTestRunServiceListRunResultsRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceListRunResults(requestParameters.productId, requestParameters.runSeq, requestParameters.status, requestParameters.search, requestParameters.identityKey, requestParameters.latestOnly, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceListTestRunsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceListTestRuns(requestParameters: TestRunServiceApiTestRunServiceListTestRunsRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceListTestRuns(requestParameters.productId, requestParameters.status, requestParameters.environment, requestParameters.branch, requestParameters.search, requestParameters.paginationPageSize, requestParameters.paginationPageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TestRunServiceApiTestRunServiceReportResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testRunServiceReportResults(requestParameters: TestRunServiceApiTestRunServiceReportResultsRequest, options?: RawAxiosRequestConfig) {
        return TestRunServiceApiFp(this.configuration).testRunServiceReportResults(requestParameters.productId, requestParameters.runSeq, requestParameters.reportResultsBody, options).then((request) => request(this.axios, this.basePath));
    }
}

