name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
        package: [commons, playwright, vitest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '${{ matrix.node }}' }
      - run: npm ci
      - run: npm run build -w commons -w playwright -w vitest
      - run: npm run lint -w ${{ matrix.package }}
      - run: npm run test -w ${{ matrix.package }}
